Repository jupyterlite/jupyterlite, pull requests merged in 2021-06, with the labels that each got.

#162 Pyolite: Fix Matplotlib
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
Labels: bug

#166 Update labels used in the template issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: maintenance

#164 Update to Plotly 5.0.0 final on the demo site
  docs/environment.yml
  examples/pyolite - plotly.ipynb
Labels: enhancement

#170 Investigate RTD build issues
  .binder/environment.yml
  app/lab/favicon.ico
  docs/conf.py
  dodo.py
  py/jupyterlite/src/jupyterlite/addons/settings.py
Labels: maintenance

#169 Add changelog for `v0.1.0a0`
  CHANGELOG.md
Labels: documentation

#172 Split up CI into multiple jobs, test on more platforms
  .binder/environment.yml
  .github/workflows/build.yml
  docs/environment.yml
  dodo.py
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/constants.py
  pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  requirements-test.txt
Labels: maintenance

#173 fix up copy, rename, delete for directories
  packages/contents/src/contents.ts
Labels: bug

#175 add --user for initial pip install in CI
  .github/workflows/build.yml
Labels: maintenance

#177 Add name to the top-level `package.json`
  package.json
Labels: maintenance

#179 Make the Changelog compatible with Jupyter Releaser
  CHANGELOG.md
Labels: maintenance

#181 Add changelog for v0.1.0a1
  CHANGELOG.md
Labels: documentation

#184 improve python distribution artifacts
  .binder/environment.yml
  .github/workflows/build.yml
  README.md
  docs/deploying.md
  dodo.py
  py/jupyterlite/README.md
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/addons/base.py
  requirements-build.txt
Labels: maintenance

#188 Update doit default tasks, upload demo app, contributing docs
  .github/workflows/build.yml
  CONTRIBUTING.md
  dodo.py
Labels: maintenance

#189 Add link to the demo GitHub Pages repo
  docs/deploying.md
Labels: documentation

#190 Handle copying multiple themes
  py/jupyterlite/src/jupyterlite/addons/federated_extensions.py
Labels: bug

#180 Add JupyterLab Miami Nights theme to the demo site, fix theme unloading
  .binder/environment.yml
  docs/environment.yml
  packages/theme/src/manager.ts
Labels: bug, enhancement

#191 Add screencasts to the README
  README.md
  py/jupyterlite/README.md
Labels: documentation

#192 Add changelog for v0.1.0a2
  CHANGELOG.md
Labels: documentation

#200 Resolve absolute path of `out_dir`
  py/jupyterlite/src/jupyterlite/app.py
Labels: bug
