Repository jupyterlite/jupyterlite, pull requests merged in 2021-09, with the labels that each got.

#313 Add support for code consoles in Retro
  app/retro/consoles/favicon.ico
  app/retro/consoles/index.html
  app/retro/consoles/jupyter-lite.json
  app/retro/index.template.js
  app/retro/package.json
  packages/retro-application-extension/package.json
  packages/retro-application-extension/src/index.ts
  yarn.lock
Labels: new

#319 Add Jupyter Releaser config
  .bumpversion.cfg
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  app/lab/package.json
  app/retro/package.json
  buildutils/package.json
  buildutils/src/ensure-repo.ts
  buildutils/tsconfig.json
  dodo.py
  package.json
  packages/application-extension/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/p5-kernel/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/retro-application-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/ui-components/package.json
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/__init__.py
  pyproject.toml
  scripts/bump-version.py
  tsconfig.eslint.json
  yarn.lock
Labels: maintenance

#327 Lint changelog in `after-build-changelog`
  pyproject.toml
Labels: maintenance

#329 Add `CHANGELOG.md` to `.prettierignore`, fix `appVersion`
  .prettierignore
  app/jupyter-lite.json
  pyproject.toml
  scripts/bump-version.py
Labels: documentation

#330 Fix display of XML files
  packages/contents/src/contents.ts
Labels: bug

#331 Automated Changelog Entry for 0.1.0a8 on main
  CHANGELOG.md
Labels: documentation

#334 fixed typo in logging call
  py/jupyterlite/src/jupyterlite/addons/contents.py
Labels: bug

#337 Update release instructions
  RELEASE.md
Labels: documentation

#338 Update to Pyodide 0.18.1
  app/jupyterlite.schema.v0.json
  packages/pyolite-kernel-extension/src/index.ts
Labels: maintenance

#344 Sync the demo site environment
  .binder/environment.yml
  examples/jupyter_lite_config.json
  examples/pyolite - ipyvuetify.ipynb
Labels: maintenance

#351 Automated Changelog Entry for 0.1.0a9 on main
  CHANGELOG.md
Labels: documentation

#354 Translation fixes
  packages/translation/src/translation.ts
  py/jupyterlite/src/jupyterlite/addons/translation.py
Labels: bug
