Repository jupyterlite/jupyterlite, pull requests merged in 2021-08, with the labels that each got.

#274 Upgrade to Pyodide 0.18.0
  .binder/environment.yml
  .github/workflows/build.yml
  .gitignore
  app/jupyterlite.schema.v0.json
  docs/environment.yml
  examples/ipyleaflet.ipynb
  examples/jupyter_lite_config.json
  examples/pyolite - altair.ipynb
  examples/pyolite - emscripten-filesystem.ipynb
  examples/pyolite - folium.ipynb
  examples/pyolite - plotly.ipynb
  packages/pyolite-kernel-extension/src/index.ts
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement

#302 Upgrade to JupyterLab 3.1.9, RetroLab 0.3.1
  .binder/environment.yml
  app/lab/package.json
  app/retro/package.json
  buildutils/package.json
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/p5-kernel/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/retro-application-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  yarn.lock
Labels: maintenance

#309 Add ipyvuetify example notebook
  .binder/environment.yml
  examples/card.vue
  examples/fruit-selector.vue
  examples/jupyter_lite_config.json
  examples/pyolite - ipyvuetify.ipynb
Labels: documentation
