Repository jupyterlite/jupyterlite, pull requests merged in 2021-12, with the labels that each got.

#426 Bump Python packages with `tbump`
  .prettierignore
  package.json
  packages/pyolite-kernel/package.json
  packages/pyolite-kernel/py/piplite/pyproject.toml
  packages/pyolite-kernel/py/pyolite/pyproject.toml
  scripts/bump-version.py
Labels: maintenance

#427 Respect app name, WebRTC Signaling Server, schema updates
  app/jupyterlite.schema.v0.json
  app/lab/index.template.js
  app/retro/index.template.js
  docs/rtc/index.md
  examples/jupyter_lite_config.json
  packages/application-extension/src/index.tsx
  py/jupyterlite/pyproject.toml
Labels: enhancement

#428 Automated Changelog Entry for 0.1.0a18 on main
  CHANGELOG.md
Labels: documentation
