Repository jupyterlite/jupyterlite, pull requests merged in 2021-11, with the labels that each got.

#404 Handle 404s when getting contents
  packages/contents/package.json
  packages/contents/src/contents.ts
  packages/contents/src/tokens.ts
  packages/server/src/server.ts
Labels: bug, api-change

#408 Automated Changelog Entry for 0.1.0a15 on main
  CHANGELOG.md
Labels: documentation

#409 Fix handling of existing folders on the server
  examples/data/Museums_in_DC.geojson
  examples/data/bar.vl.json
  examples/data/fasta-example.fasta
  examples/data/iris.csv
  examples/data/matplotlib.png
  packages/contents/src/contents.ts
Labels: bug

#410 Automated Changelog Entry for 0.1.0a16 on main
  CHANGELOG.md
Labels: documentation

#418 Enforce labels on PRs
  .github/workflows/enforce-labels.yml
Labels: maintenance

#310 add piplite for customizing pyolite packages, automate wheel management
  .binder/environment.yml
  .eslintignore
  .gitignore
  .prettierignore
  app/config-utils.js
  app/jupyterlite.schema.v0.json
  app/piplite.schema.v0.json
  app/webpack.config.js
  docs/cli.ipynb
  docs/configuring.md
  docs/developer-guide.md
  docs/environment.yml
  dodo.py
  examples/jupyter_lite_config.json
  examples/pyolite/altair.ipynb
  examples/pyolite/bqplot.ipynb
  examples/pyolite/folium.ipynb
  examples/pyolite/interactive-widgets.ipynb
  examples/pyolite/ipycanvas.ipynb
  examples/pyolite/ipycytoscape.ipynb
  examples/pyolite/ipyleaflet.ipynb
  examples/pyolite/ipympl.ipynb
  examples/pyolite/ipyvuetify.ipynb
  examples/pyolite/plotly.ipynb
  package.json
  packages/pyolite-kernel-extension/src/index.ts
  packages/pyolite-kernel/package.json
  packages/pyolite-kernel/py/piplite/piplite/__init__.py
  packages/pyolite-kernel/py/piplite/piplite/piplite.py
  packages/pyolite-kernel/py/piplite/pyproject.toml
  packages/pyolite-kernel/src/_pypi.ts
  packages/pyolite-kernel/src/declarations.d.ts
  packages/pyolite-kernel/src/kernel.ts
  packages/pyolite-kernel/src/worker.ts
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/addons/archive.py
  py/jupyterlite/src/jupyterlite/addons/base.py
  py/jupyterlite/src/jupyterlite/addons/contents.py
  py/jupyterlite/src/jupyterlite/addons/federated_extensions.py
  py/jupyterlite/src/jupyterlite/addons/piplite.py
  py/jupyterlite/src/jupyterlite/addons/settings.py
  py/jupyterlite/src/jupyterlite/addons/translation.py
  py/jupyterlite/src/jupyterlite/app.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/constants.py
  py/jupyterlite/src/jupyterlite/tests/test_piplite.py
  requirements-build.txt
  scripts/bump-version.py
Labels: enhancement, performance

#417 Add `pdf-extension`
  app/lab/package.json
  examples/data/plot.pdf
  yarn.lock
Labels: enhancement

#419 Self-hosting MathJax
  .binder/environment.yml
  docs/cli.ipynb
  docs/configuring.md
  docs/environment.yml
  dodo.py
  examples/jupyter_lite_config.json
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/addons/mathjax.py
  py/jupyterlite/src/jupyterlite/app.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/tests/test_mathjax.py
  requirements-docs.txt
Labels: enhancement

#421 Version piplite with the `bump-version` script
  .bumpversion.cfg
  scripts/bump-version.py
Labels: maintenance

#423 Automated Changelog Entry for 0.1.0a17 on main
  CHANGELOG.md
Labels: documentation

#424 Fix false positive for non-prebuilt extensions in wheels, MathJax check
  py/jupyterlite/src/jupyterlite/addons/federated_extensions.py
  py/jupyterlite/src/jupyterlite/addons/mathjax.py
  py/jupyterlite/src/jupyterlite/addons/static.py
  py/jupyterlite/src/jupyterlite/tests/test_federated.py
Labels: enhancement
