Repository jupyterlite/jupyterlite, pull requests merged in 2021-07, with the labels that each got.

#198 Add `jupyterlab-kernelspy` to the demo site
  .binder/environment.yml
  docs/environment.yml
Labels: enhancement

#206 move more path logic to traitlets
  .binder/environment.yml
  py/jupyterlite/src/jupyterlite/app.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/trait_types.py
Labels: maintenance

#203 DOC Deploy to gitlab pages
  docs/deploying.md
Labels: documentation

#204 Add tbump configuration to bump the jupyterlite Python package
  py/jupyterlite/pyproject.toml
Labels: maintenance

#212 Hoist port and base_url to CLI
  docs/cli.ipynb
  py/jupyterlite/src/jupyterlite/addons/serve.py
  py/jupyterlite/src/jupyterlite/app.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/tests/conftest.py
  py/jupyterlite/src/jupyterlite/tests/test_serve.py
Labels: enhancement

#171 Use IPython in Pyolite kernel
  examples/pyolite.ipynb
  examples/renderers.ipynb
  packages/kernel/src/kernel.ts
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
  packages/pyolite-kernel/py/pyolite/pyolite/display.py
  packages/pyolite-kernel/py/pyolite/pyolite/interpreter.py
  packages/pyolite-kernel/py/pyolite/pyolite/kernel.py
  packages/pyolite-kernel/py/pyolite/pyolite/patches.py
  packages/pyolite-kernel/src/kernel.ts
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement

#213 Add changelog for 0.1.0a3
  CHANGELOG.md
Labels: documentation

#217 Skip serve tests on MacOS CI
  py/jupyterlite/src/jupyterlite/tests/test_serve.py
Labels: maintenance

#214 Refactor the kernel implementation
  packages/javascript-kernel/src/kernel.ts
  packages/kernel/src/kernel.ts
  packages/kernel/src/tokens.ts
  packages/p5-kernel/src/kernel.ts
  packages/pyolite-kernel/src/kernel.ts
Labels: enhancement

#220 Cleanup the Plotly example
  examples/pyolite - plotly.ipynb
Labels: documentation

#219 Add ipympl example
  .binder/environment.yml
  docs/environment.yml
  examples/ipympl.ipynb
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
Labels: documentation, enhancement

#228 Add docs to deploy on Netlify
  docs/deploying.md
Labels: documentation

#230 Add status section to the README
  README.md
Labels: documentation

#231 Update links to point to the organization
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  app/index.html
  app/package.json
  buildutils/package.json
  docs/configuring.md
  docs/deploying.md
  examples/pyolite - altair.ipynb
  package.json
  packages/_metapackage/package.json
  packages/application-extension/package.json
  packages/application-extension/src/index.tsx
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/javascript-kernel/src/kernel.ts
  packages/kernel/package.json
  packages/p5-kernel-extension/package.json
  packages/p5-kernel/package.json
  packages/p5-kernel/src/kernel.ts
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/pyolite-kernel/py/ipykernel/pyproject.toml
  packages/pyolite-kernel/py/nbformat/pyproject.toml
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
  packages/pyolite-kernel/py/pyolite/pyproject.toml
  packages/pyolite-kernel/py/widgetsnbextension/pyproject.toml
  packages/pyolite-kernel/src/kernel.ts
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/theme-extension/package.json
  packages/theme/package.json
  packages/ui-components/package.json
  py/jupyterlite/README.md
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/addons/federated_extensions.py
Labels: documentation

#232 Automated Changelog Entry for 0.1.0-alpha.4 on main
  CHANGELOG.md
Labels: documentation

#205 Remove the custom theme plugin
  app/config-utils.js
  app/lab/index.template.js
  app/lab/package.json
  app/retro/index.template.js
  app/retro/jupyter-lite.json
  app/retro/package.json
  app/webpack.config.js
  packages/_metapackage/package.json
  packages/_metapackage/src/index.ts
  packages/_metapackage/tsconfig.json
  packages/theme-extension/babel.config.js
  packages/theme-extension/jest.config.js
  packages/theme-extension/package.json
  packages/theme-extension/src/index.ts
  packages/theme-extension/style/base.css
  packages/theme-extension/style/index.css
  packages/theme-extension/style/index.js
  packages/theme-extension/tsconfig.json
  packages/theme/babel.config.js
  packages/theme/jest.config.js
  packages/theme/package.json
  packages/theme/src/index.ts
  packages/theme/src/manager.ts
  packages/theme/style/base.css
  packages/theme/style/index.css
  packages/theme/style/index.js
  packages/theme/test/theme.spec.ts
  packages/theme/tsconfig.json
  packages/theme/tsconfig.test.json
  tsconfig.typedoc.json
  typedoc.json
  yarn.lock
Labels: maintenance

#226 Add patch for PIL.Image.Image._repr_png_
  examples/pyolite - images.ipynb
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
  packages/pyolite-kernel/py/pyolite/pyolite/patches.py
Labels: enhancement

#216 ipython refactor
  packages/kernel/src/kernel.ts
  packages/pyolite-kernel/py/pyolite/pyolite/interpreter.py
  packages/pyolite-kernel/py/pyolite/pyolite/kernel.py
  packages/pyolite-kernel/src/kernel.ts
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement

#109 Initial support for real time collaboration
  docs/rtc/index.md
  docs/user-guide.md
  examples/jupyter-lite.json
  packages/application-extension/package.json
  packages/application-extension/src/index.tsx
  packages/retro-application-extension/src/index.ts
  yarn.lock
Labels: enhancement

#239 Use importhook for patches
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
  packages/pyolite-kernel/py/pyolite/pyolite/patches.py
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement

#243 add inspect message
  packages/kernel/src/kernel.ts
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
  packages/pyolite-kernel/py/pyolite/pyolite/kernel.py
  packages/pyolite-kernel/src/kernel.ts
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement

#245 add is_complete message protocol
  packages/kernel/src/kernel.ts
  packages/pyolite-kernel/py/pyolite/pyolite/kernel.py
  packages/pyolite-kernel/py/pyolite/pyolite/patches.py
  packages/pyolite-kernel/src/kernel.ts
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement

#246 Add RELEASE.md
  RELEASE.md
Labels: documentation

#247 Automated Changelog Entry for 0.1.0-alpha.5 on main
  CHANGELOG.md
Labels: documentation

#250 Revert importhook for now
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
  packages/pyolite-kernel/py/pyolite/pyolite/patches.py
  packages/pyolite-kernel/src/worker.ts
Labels: bug

#251 Update changelog for v0.1.0a5
  CHANGELOG.md
Labels: documentation

#256 Add ipycytoscape example
  .binder/environment.yml
  docs/environment.yml
  examples/pyolite - ipycytoscape.ipynb
Labels: documentation

#238 Support more sources of federated_extension
  .binder/environment.yml
  .github/workflows/build.yml
  docs/cli.ipynb
  docs/doit.ipynb
  docs/environment.yml
  dodo.py
  examples/jupyter_lite_config.json
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/addons/base.py
  py/jupyterlite/src/jupyterlite/addons/federated_extensions.py
  py/jupyterlite/src/jupyterlite/addons/settings.py
  py/jupyterlite/src/jupyterlite/addons/static.py
  py/jupyterlite/src/jupyterlite/app.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/constants.py
  py/jupyterlite/src/jupyterlite/tests/conftest.py
  py/jupyterlite/src/jupyterlite/tests/fixtures/the-smallest-extension-0.1.0-py_0.tar.bz2
  py/jupyterlite/src/jupyterlite/tests/fixtures/the_smallest_extension-0.1.0-py3-none-any.whl
  py/jupyterlite/src/jupyterlite/tests/test_archive.py
  py/jupyterlite/src/jupyterlite/tests/test_federated.py
  requirements-docs.txt
  requirements-test.txt
Labels: enhancement

#257 Add ipycytoscape to the example federated extensions
  examples/jupyter_lite_config.json
Labels: documentation

#207 Upgrade to JupyterLab 3.1.0rc1
  .binder/environment.yml
  app/jupyter-lite.json
  app/jupyterlite.schema.v0.json
  app/lab/package.json
  app/retro/package.json
  buildutils/package.json
  docs/overrides.json
  dodo.py
  examples/jupyter-lite.json
  examples/overrides.json
  package.json
  packages/application-extension/package.json
  packages/application-extension/src/index.tsx
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/p5-kernel/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/retro-application-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/ui-components/package.json
  py/jupyterlite/src/jupyterlite/tests/test_cli.py
  yarn.lock
Labels: maintenance

#260 add index.html to serve message
  py/jupyterlite/src/jupyterlite/addons/serve.py
Labels: documentation

#240 Update ESLint dependencies
  .eslintignore
  .prettierignore
  lint-staged.config.js
  package.json
  yarn.lock
Labels: maintenance

#268 Add .eslintcache to the .gitignore
  .gitignore
Labels: maintenance

#263 Add RTC colors and usernames
  packages/application-extension/src/index.tsx
Labels: enhancement

#270 Add author-email to pyproject.toml
  py/jupyterlite/pyproject.toml
Labels: maintenance

#272 Fix possible typo
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
Labels: maintenance

#253 add input_request message protocol
  packages/javascript-kernel/src/kernel.ts
  packages/kernel/src/kernel.ts
  packages/kernel/src/kernels.ts
  packages/kernel/src/tokens.ts
  packages/pyolite-kernel/py/pyolite/pyolite/interpreter.py
  packages/pyolite-kernel/src/kernel.ts
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement

#278 Add the architecture diagram
  docs/architecture.md
  docs/developer-guide.md
  docs/images/jupyterlite-diagram.svg
Labels: documentation

#281 Pin jupyter widgets versions
  .binder/environment.yml
  examples/ipycanvas.ipynb
  examples/ipyleaflet.ipynb
  examples/ipympl.ipynb
  examples/pyolite - interactive-widgets.ipynb
  examples/pyolite - ipycytoscape.ipynb
Labels: maintenance

#283 Update to jupyterlab 3.1.0rc2
  .binder/environment.yml
  app/lab/package.json
  app/retro/index.template.js
  app/retro/package.json
  buildutils/package.json
  dodo.py
  examples/ipyleaflet.ipynb
  examples/jupyter_lite_config.json
  examples/pyolite - interactive-widgets.ipynb
  examples/pyolite - ipycytoscape.ipynb
  examples/pyolite - plotly.ipynb
  package.json
  packages/application-extension/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/p5-kernel/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/pyolite-kernel/py/pyolite/pyolite/__init__.py
  packages/pyolite-kernel/py/pyolite/pyolite/interpreter.py
  packages/pyolite-kernel/py/pyolite/pyolite/mocks.py
  packages/pyolite-kernel/py/pyolite/pyolite/patches.py
  packages/retro-application-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  yarn.lock
Labels: maintenance

#287 Provide `IStateDB` in retro
  app/retro/index.template.js
Labels: enhancement

#288 Switch to the organization issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: maintenance

#289 Update to RetroLab 0.3.0rc1
  app/retro/package.json
  yarn.lock
Labels: maintenance

#290 fix syntax error showing in JS console
  packages/pyolite-kernel/py/pyolite/pyolite/kernel.py
Labels: enhancement

#292 Rename --files to --contents, improve local default URLs
  app/config-utils.js
  docs/cli.ipynb
  dodo.py
  examples/jupyter_lite_config.json
  examples/retro/jupyter-lite.json
  py/jupyterlite/src/jupyterlite/addons/contents.py
  py/jupyterlite/src/jupyterlite/app.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/constants.py
  py/jupyterlite/src/jupyterlite/tests/test_cli.py
Labels: enhancement

#291 Add Changelog for 0.1.0a6
  CHANGELOG.md
Labels: documentation

#280 use bytes for nested buffers
  examples/pyolite - bqplot.ipynb
  examples/pyolite - interactive-widgets.ipynb
  packages/pyolite-kernel/py/ipykernel/ipykernel/comm.py
Labels: enhancement
