Repository jupyterlite/jupyterlite, pull requests merged in 2021-10, with the labels that each got.

#355 removed not needed methods from kernel interface
  packages/kernel/src/tokens.ts
Labels: enhancement

#356 Add workflow to post the RTD link as a PR comment
  .github/workflows/rtd-preview.yml
Labels: maintenance

#357 Fix RTD Preview workflow
  .github/workflows/rtd-preview.yml
Labels: maintenance

#352 Scaffolding for loading serverlite extensions
  app/kernelspecs/p5js.png
  app/lab/index.template.js
  app/lab/package.json
  app/retro/index.template.js
  app/retro/package.json
  docs/kernels/p5.md
  examples/jupyter_lite_config.json
  packages/_metapackage/package.json
  packages/_metapackage/src/index.ts
  packages/_metapackage/tsconfig.json
  packages/javascript-kernel-extension/package.json
  packages/p5-kernel-extension/babel.config.js
  packages/p5-kernel-extension/jest.config.js
  packages/p5-kernel-extension/package.json
  packages/p5-kernel-extension/src/index.ts
  packages/p5-kernel-extension/style/base.css
  packages/p5-kernel-extension/style/index.css
  packages/p5-kernel-extension/style/index.js
  packages/p5-kernel-extension/tsconfig.json
  packages/p5-kernel/babel.config.js
  packages/p5-kernel/jest.config.js
  packages/p5-kernel/package.json
  packages/p5-kernel/src/index.ts
  packages/p5-kernel/src/kernel.ts
  packages/p5-kernel/style/base.css
  packages/p5-kernel/style/index.css
  packages/p5-kernel/style/index.js
  packages/p5-kernel/test/p5kernel.spec.ts
  packages/p5-kernel/tsconfig.json
  packages/p5-kernel/tsconfig.test.json
  packages/server-extension/package.json
  py/jupyterlite/src/jupyterlite/addons/federated_extensions.py
  tsconfig.typedoc.json
  typedoc.json
  yarn.lock
Labels: new

#359 Automated Changelog Entry for 0.1.0a10 on main
  CHANGELOG.md
Labels: documentation

#360 Fix token name for IKernelSpecs
  packages/kernel/src/tokens.ts
Labels: maintenance

#362 Add support for `python -m jupyterlite`
  py/jupyterlite/src/jupyterlite/__main__.py
  py/jupyterlite/src/jupyterlite/tests/test_cli.py
Labels: enhancement

#361 Fix handling of disabled extensions
  app/lab/index.template.js
  app/retro/index.template.js
Labels: bug

#363 Automated Changelog Entry for 0.1.0a11 on main
  CHANGELOG.md
Labels: documentation

#365 Add `htmlviewer-extension`
  app/lab/package.json
  yarn.lock
Labels: new

#364 Add docs to deploy to Vercel
  docs/deploying.md
Labels: documentation

#366 `disabledExtension` for base retro extensions
  app/retro/index.template.js
Labels: bug

#367 Automated Changelog Entry for 0.1.0a12 on main
  CHANGELOG.md
Labels: documentation
