Repository jupyterlite/jupyterlite, pull requests merged in 2022-02, with the labels that each got.

#467 Update to JupyterLab 3.2.9 and RetroLab 0.3.19
  app/lab/package.json
  app/retro/package.json
  package.json
  packages/application-extension/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: bug

#468 Automated Changelog Entry for 0.1.0a21 on main
  CHANGELOG.md
Labels: documentation

#469 Clean up various log warnings
  .binder/environment.yml
  app/.npmignore
  app/jupyter-lite.ipynb
  app/lab/index.template.js
  app/lab/jupyter-lite.ipynb
  app/retro/consoles/jupyter-lite.ipynb
  app/retro/edit/jupyter-lite.ipynb
  app/retro/index.template.js
  app/retro/jupyter-lite.ipynb
  app/retro/notebooks/jupyter-lite.ipynb
  app/retro/tree/jupyter-lite.ipynb
  dodo.py
  examples/jupyter_lite_config.json
  examples/pyolite/bqplot.ipynb
  examples/pyolite/ipycanvas.ipynb
  examples/pyolite/ipycytoscape.ipynb
  examples/pyolite/ipyleaflet.ipynb
  examples/pyolite/ipympl.ipynb
  examples/pyolite/ipyvuetify.ipynb
  examples/pyolite/plotly.ipynb
  packages/application-extension/src/index.tsx
  packages/pyolite-kernel/src/kernel.ts
  packages/pyolite-kernel/src/worker.ts
  py/jupyterlite/pyproject.toml
  ui-tests/test/contents.test.ts
Labels: maintenance

#474 Build all apps in single webpack
  .eslintignore
  .gitignore
  .prettierignore
  app/.npmignore
  app/config-utils.js
  app/jupyter-lite.json
  app/jupyterlite.schema.v0.json
  app/lab/index.html
  app/lab/jupyter-lite.json
  app/lab/package.json
  app/package.json
  app/retro/consoles/index.html
  app/retro/consoles/jupyter-lite.json
  app/retro/edit/index.html
  app/retro/edit/jupyter-lite.json
  app/retro/jupyter-lite.json
  app/retro/notebooks/index.html
  app/retro/notebooks/jupyter-lite.json
  app/retro/package.json
  app/retro/tree/index.html
  app/retro/tree/jupyter-lite.json
  app/webpack.config.js
  docs/configuring.md
  dodo.py
  examples/jupyter_lite_config.json
  package.json
  packages/pyolite-kernel/src/kernel.ts
  py/jupyterlite/src/jupyterlite/addons/federated_extensions.py
  py/jupyterlite/src/jupyterlite/addons/settings.py
  py/jupyterlite/src/jupyterlite/constants.py
  py/jupyterlite/src/jupyterlite/tests/test_federated.py
  yarn.lock
Labels: maintenance, performance

#476 Automated Changelog Entry for 0.1.0a22 on main
  CHANGELOG.md
Labels: documentation

#477 Add cache busting, cut some fallback fonts
  .gitignore
  app/.npmignore
  app/config-utils.js
  app/lab/index.template.html
  app/lab/package.json
  app/package.json
  app/retro/consoles/index.template.html
  app/retro/edit/index.template.html
  app/retro/notebooks/index.template.html
  app/retro/package.json
  app/retro/tree/index.template.html
  app/webpack.config.js
  dodo.py
  examples/jupyter_lite_config.json
  package.json
  yarn.lock
Labels: enhancement, maintenance, performance

#493 Update lite badge in the RTD PR comment
  .github/workflows/rtd-preview.yml
Labels: maintenance

#490 Update mock socket, lerna, use registry.npmjs.org
  .yarnrc
  dodo.py
  examples/jupyter_lite_config.json
  package.json
  packages/kernel/package.json
  packages/kernel/src/kernels.ts
  packages/server/package.json
  packages/ui-components/style/icons/liteWordmark.svg
  ui-tests/test/utils.ts
  yarn.lock
Labels: maintenance, dependencies

#488 Update dependencies in `ui-tests/yarn.lock`
  ui-tests/package.json
  ui-tests/yarn.lock
Labels: maintenance

#494 Cleanup more dependencies
  app/lab/babel.config.js
  app/lab/jest-setup.js
  app/lab/jest.config.js
  app/lab/package.json
  app/lab/test/smoke.spec.ts
  app/lab/test/utils.ts
  app/lab/tsconfig.test.json
  app/package.json
  app/retro/babel.config.js
  app/retro/jest-setup.js
  app/retro/jest.config.js
  app/retro/package.json
  app/retro/tsconfig.test.json
  yarn.lock
Labels: maintenance

#495 Optimize docs images
  .github/workflows/build.yml
  docs/_static/theme.css
  docs/conf.py
  dodo.py
  examples/jupyter_lite_config.json
  packages/ui-components/style/icons/liteWordmark.svg
  py/jupyterlite/README.md
Labels: documentation, maintenance, performance

#500 Fix headings in CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#502 Automated Changelog Entry for 0.1.0a23 on main
  CHANGELOG.md
Labels: documentation

#507 FIx various typos
  CONTRIBUTING.md
  app/jupyter-lite.ipynb
  app/jupyterlite.schema.v0.json
  app/lab/jupyter-lite.ipynb
  app/repl/jupyter-lite.ipynb
  app/retro/consoles/jupyter-lite.ipynb
  app/retro/edit/jupyter-lite.ipynb
  app/retro/jupyter-lite.ipynb
  app/retro/notebooks/jupyter-lite.ipynb
  app/retro/tree/jupyter-lite.ipynb
  docs/deploying.md
  docs/extensions.md
  dodo.py
  examples/data/fruit-selector.vue
  examples/pyolite/ipycytoscape.ipynb
  examples/pyolite/ipyvuetify.ipynb
  examples/pyolite/plotly.ipynb
  packages/kernel/src/kernel.ts
  packages/pyolite-kernel/py/piplite/piplite/piplite.py
  packages/pyolite-kernel/py/pyolite/pyolite/kernel.py
  py/jupyterlite/src/jupyterlite/addons/archive.py
  py/jupyterlite/src/jupyterlite/tests/test_cli.py
Labels: maintenance

#505 Add `repl` to `rediraffe_redirects`
  docs/conf.py
Labels: documentation

#506 Expose the Router to be able to add new routes from third-party plugins
  packages/server-extension/src/index.ts
  packages/server/src/app.ts
  packages/server/src/index.ts
  packages/server/src/server.ts
  packages/server/src/service.ts
Labels: enhancement, api-change

#512 Fix handling of unicode characters on upload
  packages/contents/src/contents.ts
Labels: bug

#513 Automated Changelog Entry for 0.1.0a24 on main
  CHANGELOG.md
Labels: documentation

#516 Fix markdown table in the docs
  docs/kernels/index.md
Labels: documentation

#517 Automated Changelog Entry for 0.1.0b0 on main
  CHANGELOG.md
Labels: documentation

#519 Update to Pyodide 0.19.1
  app/jupyterlite.schema.v0.json
  dodo.py
  packages/pyolite-kernel-extension/src/index.ts
Labels: enhancement

#521 Update CI test matrix
  .github/actions/build-dist/action.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  app/webpack.config.js
  dodo.py
  py/jupyterlite/src/jupyterlite/tests/test_cli.py
Labels: maintenance, dependencies
