Repository jupyterlite/jupyterlite, pull requests merged in 2022-03, with the labels that each got.

#526 Ensure TypeDoc before docs job
  .github/workflows/build.yml
Labels: maintenance

#528 Update to JupyterLab 3.3.0 and RetroLab 0.3.20
  .binder/environment.yml
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/index.template.js
  app/retro/package.json
  package.json
  packages/application-extension/package.json
  packages/application-extension/src/index.tsx
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/retro-application-extension/src/index.ts
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/types/package.json
  packages/ui-components/package.json
  ui-tests/package.json
  ui-tests/test/retro.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/retro.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/retro.test.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/retro.test.ts-snapshots/tree-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance, app:retro, app:lab, app:repl

#531 Automated Changelog Entry for 0.1.0b1 on main
  CHANGELOG.md
Labels: documentation

#532 Update content creating method in `_getServerContents`
  packages/contents/src/contents.ts
Labels: bug, performance

#541 Minor contents refactoring, skip dedupe on binder
  .binder/postBuild
  dodo.py
  examples/jupyter_lite_config.json
  packages/contents/src/contents.ts
  packages/contents/src/tokens.ts
  yarn.lock
Labels: maintenance, performance

#538 Delay commands notified in retrolab
  packages/retro-application-extension/src/index.ts
Labels: bug

#557 WebPack tweaks for fonts, licenses, Windows
  .binder/environment.yml
  .github/workflows/win-dev.yml
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  app/webpack.config.js
  dodo.py
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/contents/src/contents.ts
  packages/contents/src/tokens.ts
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance

#558 Automated Changelog Entry for 0.1.0b3 on main
  CHANGELOG.md
Labels: documentation

#562 Clarify RTC config setting
  docs/rtc/index.md
Labels: documentation

#563 Update development server options
  .prettierignore
  CONTRIBUTING.md
  docs/cli.ipynb
  dodo.py
  package.json
  py/jupyterlite/src/jupyterlite/addons/serve.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/tests/test_serve.py
Labels: maintenance

#572 Automated Changelog Entry for 0.1.0b4 on main
  CHANGELOG.md
Labels: documentation

#573 Fix typo for the `--piplite-wheels` CLI flag in the docs
  docs/configuring.md
Labels: documentation

#580 [#86] Update the "try lite now" SVG badge and add a "launch lite" SVG badge
  docs/_static/badge-launch.svg
  docs/_static/badge.svg
Labels: enhancement

#583 ensure addons can be configured, more docs
  docs/cli-addons.md
  docs/developer-guide.md
  docs/extensions.md
  examples/jupyter_lite_config.json
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/addons/base.py
  py/jupyterlite/src/jupyterlite/constants.py
  py/jupyterlite/src/jupyterlite/manager.py
  py/jupyterlite/src/jupyterlite/tests/test_extend_addon.py
Labels: documentation
