Repository jupyterlite/jupyterlite, pull requests merged in 2022-06, with the labels that each got.

#657 Fix the kernelspecs response
  packages/server-extension/src/index.ts
Labels: bug

#659 Automated Changelog Entry for 0.1.0b8 on main
  CHANGELOG.md
Labels: documentation

#660 Simplify kernelspecs
  packages/javascript-kernel-extension/src/index.ts
  packages/pyolite-kernel-extension/src/index.ts
Labels: maintenance

#661 Update to JupyterLab 3.4.3
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: enhancement

#666 Fix CSV file upload
  packages/contents/src/tokens.ts
Labels: enhancement

#669 Allow for using `micromamba` for the dev setup
  dodo.py
Labels: maintenance

#655 Implement a custom Emscripten File System which communicates with the JupyterLab Content Manager, giving file access to pyolite
  app/services.js
  docs/howto/content/python.md
  dodo.py
  examples/jupyter_lite_config.json
  examples/pyolite/data/countries.geo.json
  examples/pyolite/data/nations.json
  examples/pyolite/ipyleaflet.ipynb
  examples/pyolite/virtual_drive.ipynb
  packages/contents/src/contents.ts
  packages/contents/src/drivefs.ts
  packages/contents/src/index.ts
  packages/kernel/package.json
  packages/kernel/src/kernel.ts
  packages/kernel/src/kernels.ts
  packages/kernel/src/kernelspecs.ts
  packages/kernel/src/tokens.ts
  packages/pyolite-kernel-extension/src/index.ts
  packages/pyolite-kernel/package.json
  packages/pyolite-kernel/src/comlink.worker.ts
  packages/pyolite-kernel/src/declarations.d.ts
  packages/pyolite-kernel/src/index.ts
  packages/pyolite-kernel/src/kernel.ts
  packages/pyolite-kernel/src/tokens.ts
  packages/pyolite-kernel/src/worker.ts
  packages/pyolite-kernel/tsconfig.json
  packages/server-extension/src/index.ts
  packages/server/src/index.ts
  packages/server/src/serviceworker.ts
  packages/server/src/tokens.ts
  packages/session/package.json
  packages/session/src/sessions.ts
  yarn.lock
Labels: enhancement

#670 Add configurable fileTypes for upload and HTTP serving
  app/jupyterlite.schema.v0.json
  docs/conf.py
  docs/howto/content/files.md
  examples/jupyter_lite_config.json
  packages/contents/src/contents.ts
  packages/contents/src/tokens.ts
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/addons/base.py
  py/jupyterlite/src/jupyterlite/addons/mimetypes.py
  py/jupyterlite/src/jupyterlite/addons/serve.py
  py/jupyterlite/src/jupyterlite/app.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/constants.py
Labels: enhancement

#677 Automated Changelog Entry for 0.1.0b9 on main
  CHANGELOG.md
Labels: documentation

#685 Change the Pyolite display name
  packages/pyolite-kernel-extension/src/index.ts
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-firefox-linux.png
Labels: maintenance

#672 Add Gitpod configuration
  .gitpod.yml
  dodo.py
Labels: documentation, enhancement

#688 Fix broken link to documentation in README
  README.md
  py/jupyterlite/README.md
Labels: documentation

#686 Caching service worker
  app/icon-120x120.png
  app/icon-512x512.png
  app/lab/favicon.ico
  app/lab/index.template.html
  app/manifest.webmanifest
  app/repl/index.template.html
  app/services.js
Labels: enhancement

#689 Add a note about `.nojekyll` to the documentation
  docs/quickstart/deploy.md
Labels: documentation

#691 add config docs to getting started
  docs/quickstart/configure.md
  docs/quickstart/index.md
Labels: documentation

#692 Automated Changelog Entry for 0.1.0b10 on main
  CHANGELOG.md
Labels: documentation
