Repository jupyterlite/jupyterlite, pull requests merged in 2022-08, with the labels that each got.

#746 Upgrade to jupyterlab 3.4.4
  .binder/environment.yml
  .eslintrc.js
  .github/actions/build-dist/action.yml
  .github/workflows/build.yml
  .github/workflows/win-dev.yml
  app/lab/favicon.ico
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  dodo.py
  examples/jupyter_lite_config.json
  examples/overrides.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite/pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance, upstream, dependencies

#753 Refactor drivefs API
  app/services.js
  packages/contents/src/drivefs.ts
  packages/server-extension/src/index.ts
Labels: bug, enhancement

#755 Docs: fix path to `overrides.json`
  docs/howto/configure/settings.md
Labels: documentation, question

#758 Change kernel from notebook
  packages/session/src/sessions.ts
Labels: bug

#761 Update GitHub Pages config in the quickstart guide
  docs/quickstart/deploy.md
Labels: documentation

#765 update to jupyterlab 3.4.5
  .binder/environment.yml
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance, dependencies

#756 Upgrade to pyodide 0.21.0
  app/jupyterlite.schema.v0.json
  dodo.py
  examples/jupyter_lite_config.json
  packages/contents/src/contents.ts
  packages/contents/src/drivefs.ts
  packages/pyolite-kernel-extension/src/index.ts
  packages/pyolite-kernel/py/piplite/piplite/piplite.py
  packages/server-extension/src/index.ts
  py/jupyterlite/src/jupyterlite/addons/pyodide.py
  py/jupyterlite/src/jupyterlite/constants.py
Labels: enhancement

#769 Automated Changelog Entry for 0.1.0b12 on main
  CHANGELOG.md
Labels: documentation

#771 Document browser console error when no contents is provided
  docs/howto/content/files.md
Labels: documentation

#775 Properly download binary content
  packages/application-extension/src/index.tsx
Labels: bug

#780 feat: bump to pyodide 0.21.1
  app/jupyterlite.schema.v0.json
  dodo.py
  packages/pyolite-kernel-extension/src/index.ts
Labels: maintenance

#782 update to pyodide 0.21.2
  app/jupyterlite.schema.v0.json
  dodo.py
  packages/pyolite-kernel-extension/src/index.ts
Labels: maintenance, upstream, dependencies
