Repository jupyterlite/jupyterlite, pull requests merged in 2022-07, with the labels that each got.

#704 make requests_cache import best-effort for pypy
  dodo.py
Labels: maintenance, dependencies

#698 Remove hardcoded default kernel
  app/jupyter-lite.json
  app/jupyterlite.schema.v0.json
  packages/kernel/package.json
  packages/kernel/src/kernelspecs.ts
  packages/kernel/src/tokens.ts
  ui-tests/test/kernels.spec.ts
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-firefox-linux.png
Labels: enhancement

#707 Docs howto content: example jupyter_lite_config.json must be JSON
  docs/howto/content/files.md
Labels: documentation

#716 Deduplicate `yarn.lock`
  yarn.lock
Labels: maintenance

#715 Allow worker.js to work with pyodide.mjs
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement

#714 Fix handling of JSON files
  app/services.js
  packages/server-extension/src/index.ts
Labels: bug

#690 Fix micromamba environment on Gitpod
  .gitpod.yml
Labels: maintenance

#719 Automated Changelog Entry for 0.1.0b11 on main
  CHANGELOG.md
Labels: documentation

#726 Update no wheels found error message
  py/jupyterlite/src/jupyterlite/app.py
Labels: maintenance

#728 Declare will_fetch early
  py/jupyterlite/src/jupyterlite/addons/pyodide.py
Labels: bug

#724 Serves Python server instead of Nodejs
  dodo.py
  package.json
Labels: bug

#722 Extra Meta Info for Developers
  CONTRIBUTING.md
Labels: documentation

#733 Bugfix:Make input work again
  packages/pyolite-kernel/src/worker.ts
Labels: bug

#734 Add JupyterLab-github to the federated extensions
  examples/jupyter_lite_config.json
Labels: documentation

#748 Fix ipycanvas example
  examples/pyolite/ipycanvas.ipynb
Labels: documentation
