Repository jupyterlite/jupyterlite, pull requests merged in 2022-05, with the labels that each got.

#611 Switch to `standby: 'never'` for the server polling to ensure kernel specs are ready
  app/bootstrap.js
  app/config-utils.js
  app/lab/index.template.js
  app/repl/index.template.js
  app/retro/index.template.js
  app/webpack.config.js
  packages/kernel/src/kernelspecs.ts
  packages/repl-extension/src/index.ts
  packages/server-extension/src/index.ts
  packages/server/src/app.ts
Labels: bug

#626 Update to JupyterLab 3.4
  .binder/environment.yml
  app/jupyter-lite.json
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/index.template.js
  app/retro/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite/pyproject.toml
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  yarn.lock
Labels: enhancement

#631 Automated Changelog Entry for 0.1.0b7 on main
  CHANGELOG.md
Labels: documentation

#629 Save files before downloading
  packages/application-extension/src/index.tsx
Labels: enhancement

#634 Allow bot PRs to be automatically labeled
  .github/workflows/enforce-labels.yml
Labels: maintenance

#644 Drop bumpversion for bumping versions, fix conda extensions
  .bumpversion.cfg
  RELEASE.md
  docs/cli.ipynb
  examples/jupyter_lite_config.json
  packages/pyolite-kernel/py/piplite/pyproject.toml
  packages/pyolite-kernel/py/pyolite/pyproject.toml
  py/jupyterlite/src/jupyterlite/__init__.py
  py/jupyterlite/src/jupyterlite/addons/base.py
  pyproject.toml
  scripts/bump-version.py
  ui-tests/jupyter_lite_config.json
Labels: maintenance

#640 Update to JupyterLab 3.4.2, add `documentsearch-extension`
  .binder/environment.yml
  app/jupyter-lite.json
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#654 Fix signature for pyplot.show in Matplotlib
  packages/pyolite-kernel/py/pyolite/pyolite/patches.py
Labels: enhancement
