Repository jupyterlite/jupyterlite, pull requests merged in 2022-12, with the labels that each got.

#911 Pyolite - Matplotlib: Setup inline backend by default
  packages/pyolite-kernel/py/pyolite/pyolite/patches.py
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement

#913 Remove `Image` hacks, vendor and use upstream `ipykernel.jsonutil`
  packages/pyolite-kernel/py/ipykernel/ipykernel/jsonutil.py
  packages/pyolite-kernel/py/pyolite/pyolite/display.py
  packages/pyolite-kernel/py/pyolite/pyolite/patches.py
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement, performance, kernel:pyolite

#916 Resolve example package lists, update matplotlib example
  examples/jupyter_lite_config.json
  examples/pyolite/matplotlib.ipynb
Labels: documentation, maintenance

#923 Update to Playwright 1.29
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/test/contents.test.ts
  ui-tests/test/general.test.ts
  ui-tests/test/kernels.spec.ts
  ui-tests/test/repl.test.ts
  ui-tests/test/retro.test.ts
  ui-tests/test/utils.ts
  ui-tests/yarn.lock
Labels: maintenance

#917 add @jupyterlite/contents to list of singleton packages
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  app/webpack.config.js
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/src/worker.ts
  yarn.lock
Labels: enhancement, api-change

#924 Update to JupyterLab 3.5.2
  .binder/environment.yml
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite/pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#900 do not signal `ready` until initialize completes
  packages/kernel/src/kernels.ts
  packages/pyolite-kernel/src/kernel.ts
Labels: enhancement

#928 Fix Gitpod setup task
  .gitpod.yml
Labels: maintenance

#931 Add name to the top-level `pyproject.toml`
  pyproject.toml
Labels: maintenance
