Repository jupyterlite/jupyterlite, pull requests merged in 2022-01, with the labels that each got.

#433 Update to pyodide 0.19.0
  .prettierignore
  app/jupyterlite.schema.v0.json
  dodo.py
  examples/jupyter_lite_config.json
  examples/pyolite/altair.ipynb
  examples/pyolite/emscripten-filesystem.ipynb
  packages/pyolite-kernel-extension/src/index.ts
  packages/pyolite-kernel/package.json
  packages/pyolite-kernel/py/nbformat/README.md
  packages/pyolite-kernel/py/nbformat/nbformat/__init__.py
  packages/pyolite-kernel/py/nbformat/pyproject.toml
  packages/pyolite-kernel/py/piplite/piplite/piplite.py
  packages/pyolite-kernel/py/pyolite/pyolite/mocks.py
  packages/pyolite-kernel/src/_pypi.ts
  packages/pyolite-kernel/src/worker.ts
Labels: enhancement, upstream

#441 Update to JupyerLab 3.2.6 and RetroLab 0.3.16
  .binder/environment.yml
  app/lab/package.json
  app/retro/package.json
  package.json
  packages/application-extension/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/retro-application-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  ui-tests/test/retro.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/retro.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/retro.test.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/retro.test.ts-snapshots/tree-firefox-linux.png
  yarn.lock
Labels: maintenance

#442 Automated Changelog Entry for 0.1.0a19 on main
  CHANGELOG.md
Labels: documentation

#432 [DOCS] Adding introductory documentation to the launch buttons
  docs/_templates/launch.html
  examples/README.md
  examples/intro-retro.ipynb
  examples/intro.ipynb
Labels: documentation

#448 Disable jedi to fix tab completion issue
  packages/pyolite-kernel/py/pyolite/pyolite/interpreter.py
Labels: bug

#449 Allow contents and settings storage names to be configured
  app/jupyterlite.schema.v0.json
  docs/configuring.md
  dodo.py
  examples/jupyter_lite_config.json
  packages/contents/src/contents.ts
  packages/server-extension/package.json
  packages/server-extension/src/index.ts
  packages/settings/src/settings.ts
Labels: enhancement

#453 Update to `jupyterlab-fasta==3.2.0` in docs app
  examples/jupyter_lite_config.json
Labels: bug

#454 Automated Changelog Entry for 0.1.0a20 on main
  CHANGELOG.md
Labels: documentation

#456 Update Read the Docs configuration (automatic)
  .readthedocs.yml
Labels: documentation, maintenance
