Repository jupyterlite/jupyterlite, pull requests merged in 2022-09, with the labels that each got.

#786 Improve the Gitpod setup
  .gitpod.yml
Labels: maintenance

#787 Point to deploy doc in README.md
  README.md
  py/jupyterlite/README.md
Labels: documentation

#791 Update to JupyterLab 3.4.6
  .binder/environment.yml
  app/kernelspecs/javascript.svg
  app/kernelspecs/python.png
  app/kernelspecs/python.svg
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  dodo.py
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel-extension/src/index.ts
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-firefox-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-firefox-linux.png
  yarn.lock
Labels: maintenance

#793 Update demos to ipywidgets 8, use widgetsnbextension shim
  .binder/environment.yml
  dodo.py
  examples/jupyter_lite_config.json
  packages/pyolite-kernel/package.json
  packages/pyolite-kernel/py/widgetsnbextension3/widgetsnbextension/LICENSE
  packages/pyolite-kernel/py/widgetsnbextension3/widgetsnbextension/README.md
  packages/pyolite-kernel/py/widgetsnbextension3/widgetsnbextension/pyproject.toml
  packages/pyolite-kernel/py/widgetsnbextension3/widgetsnbextension/widgetsnbextension/__init__.py
  packages/pyolite-kernel/py/widgetsnbextension4/widgetsnbextension/LICENSE
  packages/pyolite-kernel/py/widgetsnbextension4/widgetsnbextension/README.md
  packages/pyolite-kernel/py/widgetsnbextension4/widgetsnbextension/pyproject.toml
  packages/pyolite-kernel/py/widgetsnbextension4/widgetsnbextension/widgetsnbextension/__init__.py
  packages/pyolite-kernel/src/_pypi.ts
Labels: documentation

#809 Update to JupyterLab 3.4.7
  .binder/environment.yml
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance, upstream, dependencies

#810 chore: update to Pyodide 0.21.3
  app/jupyterlite.schema.v0.json
  dodo.py
  packages/pyolite-kernel-extension/src/index.ts
Labels: maintenance

#813 Automated Changelog Entry for 0.1.0b13 on main
  CHANGELOG.md
Labels: documentation

#817 New gitlab minimal example
  docs/howto/deployment/gitlab.md
Labels: documentation

#821 Condition all addon tasks for well-formedness
  py/jupyterlite/src/jupyterlite/addons/archive.py
  py/jupyterlite/src/jupyterlite/addons/base.py
  py/jupyterlite/src/jupyterlite/addons/contents.py
  py/jupyterlite/src/jupyterlite/addons/federated_extensions.py
  py/jupyterlite/src/jupyterlite/addons/lite.py
  py/jupyterlite/src/jupyterlite/addons/mathjax.py
  py/jupyterlite/src/jupyterlite/addons/mimetypes.py
  py/jupyterlite/src/jupyterlite/addons/piplite.py
  py/jupyterlite/src/jupyterlite/addons/pyodide.py
  py/jupyterlite/src/jupyterlite/addons/report.py
  py/jupyterlite/src/jupyterlite/addons/serve.py
  py/jupyterlite/src/jupyterlite/addons/settings.py
  py/jupyterlite/src/jupyterlite/addons/static.py
  py/jupyterlite/src/jupyterlite/addons/translation.py
  py/jupyterlite/src/jupyterlite/tests/test_cli.py
Labels: enhancement

#823 Update development Python dependencies
  .binder/environment.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/ui-tests.yml
  .github/workflows/win-dev.yml
  CONTRIBUTING.md
  docs/environment.yml
  dodo.py
  examples/jupyter_lite_config.json
  packages/pyolite-kernel/src/_pypi.ts
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/manager.py
  py/jupyterlite/src/jupyterlite/tests/test_extend_addon.py
  requirements-build.txt
  requirements-docs.txt
Labels: maintenance, dependencies

#824 Update `lerna` to `^5.5.4`
  package.json
  yarn.lock
Labels: maintenance
