Repository jupyterlite/jupyterlite, pull requests merged in 2022-10, with the labels that each got.

#828 Update JupyterLab 3.4.8
  .binder/environment.yml
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance, dependencies

#832 Add pyolite pre-transformer, %pip
  .binder/environment.yml
  docs/howto/configure/advanced/offline.md
  docs/howto/configure/simple_extensions.md
  docs/howto/python/packages.md
  docs/reference/cli.ipynb
  docs/reference/doit.ipynb
  dodo.py
  examples/data/more-requirements.txt
  examples/jupyter_lite_config.json
  examples/pyolite/data/requirements.txt
  examples/pyolite/python-packages.ipynb
  packages/pyolite-kernel/py/piplite/piplite/__init__.py
  packages/pyolite-kernel/py/piplite/piplite/cli.py
  packages/pyolite-kernel/py/piplite/piplite/piplite.py
  packages/pyolite-kernel/py/pyolite/pyolite/kernel.py
  packages/pyolite-kernel/py/pyolite/pyolite/litetransform.py
  packages/pyolite-kernel/py/widgetsnbextension3/widgetsnbextension/README.md
  packages/pyolite-kernel/py/widgetsnbextension4/widgetsnbextension/README.md
  packages/pyolite-kernel/src/worker.ts
  requirements-lint.txt
Labels: documentation, enhancement

#839 Include some more accurate file stats from ServiceWorker
  examples/jupyter_lite_config.json
  examples/pyolite/virtual_drive.ipynb
  packages/contents/src/contents.ts
  packages/contents/src/drivefs.ts
  packages/server-extension/src/index.ts
Labels: enhancement, kernel:pyolite

#833 Lint example notebooks, use %pip magic
  dodo.py
  examples/intro-retro.ipynb
  examples/intro.ipynb
  examples/javascript.ipynb
  examples/p5.ipynb
  examples/pyolite/altair.ipynb
  examples/pyolite/bqplot.ipynb
  examples/pyolite/emscripten-filesystem.ipynb
  examples/pyolite/folium.ipynb
  examples/pyolite/images.ipynb
  examples/pyolite/interactive-widgets.ipynb
  examples/pyolite/ipycanvas.ipynb
  examples/pyolite/ipycytoscape.ipynb
  examples/pyolite/ipyleaflet.ipynb
  examples/pyolite/ipympl.ipynb
  examples/pyolite/ipyvuetify.ipynb
  examples/pyolite/matplotlib.ipynb
  examples/pyolite/plotly.ipynb
  examples/pyolite/renderers.ipynb
  examples/pyolite/virtual_drive.ipynb
  examples/python.ipynb
  package.json
  packages/pyolite-kernel/py/piplite/piplite/cli.py
Labels: documentation

#844 Bump various GitHub Actions, handle new `jupyter_core`
  .github/actions/build-dist/action.yml
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/ui-tests.yml
  .github/workflows/win-dev.yml
  py/jupyterlite/src/jupyterlite/app.py
Labels: maintenance

#847 Automated Changelog Entry for 0.1.0b14 on main
  CHANGELOG.md
Labels: documentation

#848 Update to JupyterLab 3.5
  .binder/environment.yml
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite/pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement
