Repository jupyterlite/jupyterlite, pull requests merged in 2022-04, with the labels that each got.

#594 Fix handling of `get_version()`
  pyproject.toml
  scripts/bump-version.py
Labels: maintenance

#578 Update to pyodide 0.20.0
  .binder/environment.yml
  app/jupyterlite.schema.v0.json
  docs/environment.yml
  dodo.py
  examples/jupyter_lite_config.json
  examples/pyolite/emscripten-filesystem.ipynb
  packages/pyolite-kernel-extension/src/index.ts
  packages/pyolite-kernel/py/ipykernel/pyproject.toml
  packages/pyolite-kernel/py/piplite/pyproject.toml
  packages/pyolite-kernel/py/pyolite/pyolite/mocks.py
  packages/pyolite-kernel/py/pyolite/pyproject.toml
  packages/pyolite-kernel/py/widgetsnbextension/pyproject.toml
  packages/settings/src/settings.ts
  py/jupyterlite/pyproject.toml
  py/jupyterlite/src/jupyterlite/addons/piplite.py
  py/jupyterlite/src/jupyterlite/app.py
  py/jupyterlite/src/jupyterlite/constants.py
  requirements-build.txt
  scripts/bump-version.py
Labels: enhancement, upstream, performance

#593 Update overview diagram in the documentation
  docs/images/jupyterlite-diagram.svg
Labels: documentation

#603 Mention `jupyterlab-filesystem-access` in the documentation
  docs/configuring.md
Labels: documentation

#601 Add FAQ item about accessing content from Python
  docs/user-guide.md
Labels: documentation

#604 Automated Changelog Entry for 0.1.0b5 on main
  CHANGELOG.md
Labels: documentation

#614 Show in file browser when opening files on startup
  packages/application-extension/src/index.tsx
Labels: enhancement

#617 Rename default name from `Consolite` to `REPLite`
  app/repl/index.template.js
Labels: maintenance

#621 More granular way to ignore components from `sys.prefix`
  docs/configuring.md
  examples/jupyter_lite_config.json
  py/jupyterlite/src/jupyterlite/addons/base.py
  py/jupyterlite/src/jupyterlite/addons/federated_extensions.py
  py/jupyterlite/src/jupyterlite/addons/mathjax.py
  py/jupyterlite/src/jupyterlite/addons/translation.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/manager.py
  py/jupyterlite/src/jupyterlite/tests/test_extend_addon.py
  py/jupyterlite/src/jupyterlite/tests/test_federated.py
  py/jupyterlite/src/jupyterlite/tests/test_piplite.py
  ui-tests/jupyter_lite_config.json
Labels: enhancement

#623 Create and use dedicated jupyterlite i18n bundle
  packages/application-extension/src/index.tsx
  packages/repl-extension/src/index.ts
Labels: maintenance
