Repository jupyterlite/jupyterlite, pull requests merged in 2023-12, with the labels that each got.

#1267 Re-add `@jupyterlab/celltags-extension`, bump to `@jupyterlab` 4.0.9 packages
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-javascript-kernel/package.json
  yarn.lock
Labels: bug

#1271 Update to `jupyterlite-pyodide-kernel==0.2.0`
  .binder/environment.yml
  examples/jupyter_lite_config.json
  ui-tests/requirements.txt
Labels: maintenance

#1266 Adopt ruff format
  .binder/environment.yml
  .pre-commit-config.yaml
  docs/reference/cli.ipynb
  docs/reference/doit.ipynb
  examples/intro.ipynb
  examples/pyodide/bqplot.ipynb
  examples/pyodide/interactive-widgets.ipynb
  examples/pyodide/ipycanvas.ipynb
  examples/pyodide/ipyleaflet.ipynb
  examples/pyodide/ipyvuetify.ipynb
  examples/pyodide/matplotlib.ipynb
  examples/pyodide/plotly.ipynb
  examples/pyodide/virtual_drive.ipynb
  examples/python.ipynb
  package.json
  pyproject.toml
  requirements-lint.txt
Labels: maintenance

#1270 DOCS: unpin myst-nb
  docs/environment.yml
  docs/howto/configure/config_files.md
  docs/quickstart/configure.md
  requirements-docs.txt
Labels: documentation

#1264 javascript-kernel: use string repr of eval result
  packages/javascript-kernel/package.json
  packages/javascript-kernel/src/worker.ts
  yarn.lock
Labels: bug
