Repository jupyterlite/jupyterlite, pull requests merged in 2023-03, with the labels that each got.

#992 Update to Playwright 1.31.2
  ui-tests/package.json
  ui-tests/yarn.lock
Labels: maintenance

#997 Point docs to `0.1.0-beta` in the README for now
  README.md
  py/jupyterlite/README.md
Labels: documentation

#1000 Update the Pyodide kernel on the demo site
  examples/jupyter_lite_config.json
  ui-tests/jupyter_lite_config.json
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-firefox-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-firefox-linux.png
Labels: documentation

#998 Remove code references to pyolite, add BaseAddon methods
  README.md
  app/jupyterlite.schema.v0.json
  app/kernelspecs/python.svg
  app/piplite.schema.v0.json
  dodo.py
  py/jupyterlite-core/src/jupyterlite_core/addons/base.py
  py/jupyterlite/src/jupyterlite/addons/base.py
Labels: enhancement, maintenance

#1001 Update `jupyterlite` dependencies and docs
  .github/actions/build-dist/action.yml
  .github/workflows/build.yml
  .github/workflows/ui-tests.yml
  docs/howto/configure/advanced/extensions.md
  docs/howto/configure/advanced/iframe.md
  docs/howto/configure/advanced/offline.md
  docs/howto/configure/advanced/service-worker.md
  docs/howto/configure/simple_extensions.md
  docs/howto/deployment/gitlab.md
  docs/howto/deployment/vercel-netlify.md
  docs/howto/extensions/frontend.md
  docs/howto/extensions/server.md
  docs/quickstart/deploy.md
  docs/quickstart/standalone.md
  docs/reference/cli.ipynb
  dodo.py
  examples/jupyter_lite_config.json
  py/jupyterlite-core/src/jupyterlite_core/tests/test_cli.py
  py/jupyterlite/pyproject.toml
  ui-tests/jupyter_lite_config.json
Labels: maintenance

#1009 Default docs back to `latest`
  README.md
  py/jupyterlite/README.md
Labels: documentation

#1012 Add a minimal README for `jupyterlite-core`
  py/jupyterlite-core/README.md
Labels: documentation

#1014 Remove "Releasing" section from the docs
  CONTRIBUTING.md
Labels: documentation

#1015 Bootstrap the migration guide
  CHANGELOG.md
  docs/index.md
  docs/migration.md
Labels: documentation

#1016 Require Python 3.8, test on Python 3.11
  .github/actions/build-dist/action.yml
  .github/workflows/build.yml
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
Labels: maintenance

#1018 Improve documentation for installing different kernels
  docs/howto/configure/advanced/extensions.md
  docs/howto/configure/advanced/offline.md
  docs/howto/configure/advanced/service-worker.md
  docs/howto/configure/kernels.md
  docs/howto/configure/simple_extensions.md
  docs/howto/deployment/github-pages.md
  docs/howto/index.md
  docs/howto/pyodide/packages.md
  docs/howto/pyodide/pyodide.md
  docs/howto/pyodide/wheels.md
  docs/howto/xeus-python/preinstalled_packages.md
  docs/quickstart/deploy.md
  docs/quickstart/standalone.md
  docs/reference/cli.ipynb
Labels: documentation

#1021 Add `@jupyterlab/attachments` to the build
  app/lab/package.json
  app/repl/package.json
  app/retro/package.json
  yarn.lock
Labels: bug

#1026 Documentation: Minor improvements to the standalone guide
  docs/quickstart/standalone.md
Labels: documentation

#1029 Add a small mention of the p5 notebook in the documentation
  docs/quickstart/using.md
Labels: documentation

#1030 Add docs about installing the JupyterLite application on desktop and mobile
  docs/howto/configure/advanced/offline.md
  docs/quickstart/using.md
Labels: documentation
