Repository jupyterlite/jupyterlite, pull requests merged in 2023-01, with the labels that each got.

#934 Allow Addons to provide CLI aliases and flags
  .binder/environment.yml
  docs/howto/configure/advanced/offline.md
  docs/howto/extensions/cli-addons.md
  docs/howto/python/wheels.md
  docs/reference/cli.ipynb
  docs/reference/doit.ipynb
  dodo.py
  examples/jupyter_lite_config.json
  py/jupyterlite/src/jupyterlite/addons/__init__.py
  py/jupyterlite/src/jupyterlite/addons/contents.py
  py/jupyterlite/src/jupyterlite/addons/piplite.py
  py/jupyterlite/src/jupyterlite/addons/pyodide.py
  py/jupyterlite/src/jupyterlite/addons/report.py
  py/jupyterlite/src/jupyterlite/addons/static.py
  py/jupyterlite/src/jupyterlite/addons/translation.py
  py/jupyterlite/src/jupyterlite/app.py
  py/jupyterlite/src/jupyterlite/config.py
  py/jupyterlite/src/jupyterlite/manager.py
  py/jupyterlite/src/jupyterlite/tests/conftest.py
  py/jupyterlite/src/jupyterlite/tests/test_cli_aliases_flags.py
  py/jupyterlite/src/jupyterlite/tests/test_extend_addon.py
  py/jupyterlite/src/jupyterlite/tests/test_federated.py
  py/jupyterlite/src/jupyterlite/tests/test_piplite.py
  py/jupyterlite/src/jupyterlite/tests/test_pyodide.py
Labels: enhancement, api-change

#937 Update to Pyodide 0.22
  app/jupyterlite.schema.v0.json
  docs/howto/configure/advanced/offline.md
  docs/howto/content/python.md
  dodo.py
  packages/pyolite-kernel-extension/src/index.ts
  packages/pyolite-kernel/package.json
  packages/pyolite-kernel/py/piplite/piplite/cli.py
  packages/pyolite-kernel/src/worker.ts
  yarn.lock
Labels: enhancement

#939 normalize all indexed piplite wheel names
  py/jupyterlite/src/jupyterlite/addons/piplite.py
Labels: enhancement

#943 Update to lerna 6.4
  package.json
  yarn.lock
Labels: maintenance

#951 Display field in webmanifest changed to standalone to support iPadOS
  app/manifest.webmanifest
Labels: enhancement

#711 Run the JavaScript kernel in a Web Worker
  packages/javascript-kernel/package.json
  packages/javascript-kernel/src/comlink.worker.ts
  packages/javascript-kernel/src/index.ts
  packages/javascript-kernel/src/kernel.ts
  packages/javascript-kernel/src/tokens.ts
  packages/javascript-kernel/src/worker.ts
  packages/kernel/src/tokens.ts
  packages/pyolite-kernel/src/worker.ts
  yarn.lock
Labels: enhancement, api-change

#953 Fix UI tests snapshots cleaning on CI
  .github/workflows/ui-tests.yml
  ui-tests/package.json
  ui-tests/yarn.lock
Labels: maintenance

#955 Update the p5 kernel on the demo site
  dodo.py
  examples/jupyter_lite_config.json
Labels: documentation

#952 Update the JavaScript kernel display name
  README.md
  docs/quickstart/using.md
  packages/javascript-kernel-extension/src/index.ts
  py/jupyterlite/README.md
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-firefox-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-firefox-linux.png
Labels: maintenance

#964 Troubleshoot ReadTheDocs
  docs/conf.py
Labels: maintenance

#960 Update to JupyterLab 3.5.3
  .binder/environment.yml
  app/lab/package.json
  app/package.json
  app/repl/package.json
  app/retro/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/pyolite-kernel-extension/package.json
  packages/pyolite-kernel/package.json
  packages/repl-extension/package.json
  packages/retro-application-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite/pyproject.toml
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance
