Repository jupyterlite/jupyterlite, pull requests merged in 2023-10, with the labels that each got.

#1182 Bump `ipyvue` and `ipyvuetify`
  examples/jupyter_lite_config.json
Labels: documentation

#1184 Bump `ipyleaflet`
  examples/jupyter_lite_config.json
Labels: documentation

#1187 Switch from `hub` to `gh` in the Playwright snapshots update workflow
  .github/workflows/playwright-update.yml
Labels: maintenance

#1188 Add note about extension authoring in 0.2.0
  docs/migration.md
Labels: documentation

#1189 Add more UI tests
  packages/application-extension/src/index.tsx
  ui-tests/package.json
  ui-tests/test/contents.test.ts
  ui-tests/test/kernels.spec.ts
  ui-tests/test/notebook.test.ts
  ui-tests/test/utils.ts
Labels: maintenance

#1147 Remove dependency on `jupyterlite-pyodide-kernel`
  CONTRIBUTING.md
  docs/migration.md
  docs/quickstart/deploy.md
  docs/quickstart/standalone.md
  py/jupyterlite/pyproject.toml
Labels: maintenance, api-change

#1183 Clean up log messages, flaky tests on Windows
  .binder/environment.yml
  .yarnrc.yml
  docs/environment.yml
  docs/reference/cli.ipynb
  examples/pyodide/plotly.ipynb
  py/jupyterlite-core/jupyterlite_core/tests/test_archive.py
  py/jupyterlite-core/jupyterlite_core/tests/test_cli.py
  py/jupyterlite-core/jupyterlite_core/tests/test_contents.py
  py/jupyterlite-core/jupyterlite_core/tests/test_federated.py
  py/jupyterlite-core/jupyterlite_core/tests/test_mathjax.py
  requirements-test.txt
Labels: maintenance

#1193 Cleanup Mathjax
  .binder/environment.yml
  app/jupyter-lite.json
  app/jupyterlite.schema.v0.json
  docs/environment.yml
  docs/howto/configure/advanced/offline.md
  docs/howto/configure/latex.md
  docs/howto/index.md
  docs/migration.md
  docs/reference/cli.ipynb
  dodo.py
  examples/jupyter_lite_config.json
  py/jupyterlite-core/jupyterlite_core/addons/mathjax.py
  py/jupyterlite-core/jupyterlite_core/app.py
  py/jupyterlite-core/jupyterlite_core/config.py
  py/jupyterlite-core/jupyterlite_core/tests/test_mathjax.py
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-docs.txt
Labels: maintenance, api-change

#1200 Fix contents example in `jupyter_lite_config.json`
  docs/howto/configure/config_files.md
Labels: documentation

#1199 Fix opening files with a different factory
  app/edit/package.json
  packages/application-extension/package.json
  packages/application-extension/src/index.tsx
  ui-tests/test/contents.test.ts
  ui-tests/test/notebook.test.ts
  ui-tests/test/notebook.test.ts-snapshots/notebook-as-json-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/notebook-as-json-firefox-linux.png
  yarn.lock
Labels: enhancement

#1202 Fix document viewers in Notebook
  app/edit/package.json
  app/tree/package.json
  ui-tests/test/notebook.test.ts
  ui-tests/test/notebook.test.ts-snapshots/csvviewer-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/csvviewer-firefox-linux.png
  ui-tests/test/notebook.test.ts-snapshots/imageviewer-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/imageviewer-firefox-linux.png
  yarn.lock
Labels: enhancement

#1205 Update to JupyterLab 4.0.7 and Notebook 7.0.5
  .binder/environment.yml
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite-javascript-kernel/package.json
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/test/repl.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/dark-theme-firefox-linux.png
  yarn.lock
Labels: enhancement

#1198 Add UI test for MathJax
  ui-tests/test/renderers.test.ts
  ui-tests/test/renderers.test.ts-snapshots/latex-chromium-linux.png
  ui-tests/test/renderers.test.ts-snapshots/latex-firefox-linux.png
Labels: maintenance

#1212 Add `tsconfig.eslint.json` with a list of `include`
  .eslintrc.js
  tsconfig.eslint.json
Labels: maintenance

#1209 Fix handling of `default` locale
  .github/workflows/ui-tests.yml
  packages/server-extension/src/index.ts
  ui-tests/jupyter_lite_config.json
  ui-tests/requirements.txt
  ui-tests/test/translations.test.ts
Labels: bug

#1214 Update to Notebook 7.0.6, copy Jupyter Server favicons
  app/consoles/package.json
  app/edit/package.json
  app/notebooks/package.json
  app/tree/package.json
  packages/notebook-application-extension/package.json
  py/jupyterlite-core/jupyterlite_core/addons/icons.py
  py/jupyterlite-core/pyproject.toml
  ui-tests/contents/empty.ipynb
  ui-tests/jupyter_lite_config.json
  ui-tests/playwright.config.js
  ui-tests/test/notebook.test.ts
  ui-tests/test/utils.ts
  yarn.lock
Labels: bug

#1207 Fix CLI help for aliases
  py/jupyterlite-core/jupyterlite_core/app.py
Labels: bug

#1220 Load all settings from federated extensions at startup
  app/doc/tree/index.html
  app/lab/package.json
  app/webpack.config.js
  docs/howto/configure/interface_switcher.md
  docs/howto/index.md
  examples/jupyter_lite_config.json
  packages/application-extension/src/index.tsx
  packages/settings/src/settings.ts
  packages/settings/src/tokens.ts
  py/jupyterlite-core/jupyterlite_core/addons/federated_extensions.py
  py/jupyterlite-core/jupyterlite_core/constants.py
  py/jupyterlite-core/jupyterlite_core/tests/test_cli.py
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  tsconfig.eslint.json
  ui-tests/requirements.txt
  ui-tests/test/notebook.test.ts
  yarn.lock
Labels: bug

#1221 Document `extra_labextensions_path`
  docs/howto/configure/advanced/extensions.md
  docs/howto/configure/simple_extensions.md
Labels: documentation

#1230 Set `navigation_with_keys` to `False`explicitely
  docs/conf.py
Labels: documentation

#1227 Fix handling of files in custom drives
  packages/application-extension/src/index.tsx
  packages/contents/src/broadcast.ts
  packages/session/src/sessions.ts
Labels: bug

#1232 update jupyterlab trove classifiers
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite-javascript-kernel/pyproject.toml
  py/jupyterlite/pyproject.toml
Labels: maintenance

#1235 Fix extra console.log, avoid future console.log noise
  .eslintrc.js
  packages/application-extension/src/index.tsx
  packages/javascript-kernel/src/worker.ts
  packages/server-extension/src/index.ts
  packages/server/src/service-manager.ts
Labels: maintenance

#1234 Update link to Notebook 7 in the README
  README.md
Labels: documentation
