Repository jupyterlite/jupyterlite, pull requests merged in 2023-09, with the labels that each got.

#1143 Move prettier config to `package.json`, drop `trailingComma`
  .prettierrc
  app/config-utils.js
  app/webpack.config.js
  dodo.py
  package.json
  packages/application-extension/src/index.tsx
  packages/application/src/singleWidgetShell.ts
  packages/contents/src/contents.ts
  packages/contents/src/drivefs.ts
  packages/contents/src/emscripten.ts
  packages/contents/src/tokens.ts
  packages/javascript-kernel/src/kernel.ts
  packages/kernel/src/kernel.ts
  packages/kernel/src/kernels.ts
  packages/kernel/src/tokens.ts
  packages/licenses/src/licenses.ts
  packages/localforage/src/memory.ts
  packages/localforage/src/tokens.ts
  packages/repl-extension/src/index.ts
  packages/server-extension/src/index.ts
  packages/server/src/app.ts
  packages/server/src/router.ts
  packages/server/src/service-manager.ts
  packages/server/src/tokens.ts
  packages/session/src/sessions.ts
  packages/settings/src/settings.ts
  packages/translation/src/tokens.ts
  packages/translation/src/translation.ts
  scripts/serve.js
  ui-tests/test/contents.test.ts
Labels: maintenance

#1142 [0.1.x] Add bounds to the `jupyterlite-core` dependency
  py/jupyterlite/pyproject.toml
Labels: maintenance

#1144 Add a section to the migration guide for `0.2.0`
  docs/migration.md
Labels: documentation

#1146 Add bot reaction to the snapshot update comment
  .github/workflows/playwright-update.yml
  CONTRIBUTING.md
Labels: maintenance

#1010 Add a lower bound on `jupyterlite-core`
  py/jupyterlite/pyproject.toml
  pyproject.toml
Labels: maintenance

#1154 Update to JupyterLab 4.0.6 and Notebook 7.0.4
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/notebook-application-extension/src/index.ts
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-javascript-kernel/package.json
  yarn.lock
Labels: enhancement

#1159 Allow config worker url in ServiceWorkerManager
  .gitignore
  app/webpack.config.js
  docs/migration.md
  packages/server/src/service-manager.ts
  packages/server/src/tokens.ts
Labels: enhancement

#1162 Update to `jupyterlite-pyodide-kernel==0.2.0a1` on ReadTheDocs
  examples/jupyter_lite_config.json
Labels: documentation

#1164 Point to `retro` for the stable docs
  README.md
Labels: documentation

#1165 Fix docs for the new pydata sphinx theme
  docs/_static/wordmark-dark.svg
  docs/conf.py
  docs/index.md
Labels: documentation

#1167 Add version switcher to the docs
  docs/_static/switcher.json
  docs/conf.py
Labels: documentation

#1168 Backport PR #1165 on branch 0.1.x (Fix docs for the new pydata sphinx theme)
  docs/_static/wordmark-dark.svg
  docs/conf.py
  docs/index.md
Labels: documentation

#1169 Backport PR #1167 on branch 0.1.x (Add version switcher to the docs)
  docs/_static/switcher.json
  docs/conf.py
Labels: documentation

#1161 Adopt `ruff`, clean up linting
  .binder/environment.yml
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/win-dev.yml
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/conf.py
  docs/migration.md
  docs/reference/cli.ipynb
  dodo.py
  examples/pyodide/ipyleaflet.ipynb
  examples/pyodide/ipyvuetify.ipynb
  examples/pyodide/plotly.ipynb
  examples/python.ipynb
  lint-staged.config.js
  package.json
  py/jupyterlite-core/jupyterlite_core/addons/__init__.py
  py/jupyterlite-core/jupyterlite_core/addons/archive.py
  py/jupyterlite-core/jupyterlite_core/addons/base.py
  py/jupyterlite-core/jupyterlite_core/addons/contents.py
  py/jupyterlite-core/jupyterlite_core/addons/federated_extensions.py
  py/jupyterlite-core/jupyterlite_core/addons/lite.py
  py/jupyterlite-core/jupyterlite_core/addons/mathjax.py
  py/jupyterlite-core/jupyterlite_core/addons/report.py
  py/jupyterlite-core/jupyterlite_core/addons/serve.py
  py/jupyterlite-core/jupyterlite_core/addons/settings.py
  py/jupyterlite-core/jupyterlite_core/addons/static.py
  py/jupyterlite-core/jupyterlite_core/addons/translation.py
  py/jupyterlite-core/jupyterlite_core/app.py
  py/jupyterlite-core/jupyterlite_core/config.py
  py/jupyterlite-core/jupyterlite_core/manager.py
  py/jupyterlite-core/jupyterlite_core/optional.py
  py/jupyterlite-core/jupyterlite_core/tests/conftest.py
  py/jupyterlite-core/jupyterlite_core/tests/test_archive.py
  py/jupyterlite-core/jupyterlite_core/tests/test_cli.py
  py/jupyterlite-core/jupyterlite_core/tests/test_contents.py
  py/jupyterlite-core/jupyterlite_core/tests/test_extend_addon.py
  py/jupyterlite-core/jupyterlite_core/tests/test_federated.py
  py/jupyterlite-core/jupyterlite_core/tests/test_mathjax.py
  py/jupyterlite-core/jupyterlite_core/tests/test_serve.py
  py/jupyterlite-javascript-kernel/package.json
  pyproject.toml
  requirements-lint.txt
  scripts/bump-version.py
  ui-tests/build.py
  yarn.lock
Labels: maintenance

#1170 JupyterLab 4 / Notebook 7 update fixes
  app/consoles/package.json
  app/edit/package.json
  app/jupyter-lite.json
  app/lab/jupyter-lite.json
  app/notebooks/package.json
  app/repl/package.json
  app/tree/package.json
  packages/application-extension/package.json
  packages/application-extension/schema/share-file.json
  packages/application-extension/src/index.tsx
  packages/notebook-application-extension/src/index.ts
  yarn.lock
Labels: bug

#1177 Add Jupyter Notebook 7 to the migration guide
  docs/migration.md
Labels: documentation

#1176 Add missing singleton packages, fix extra newlines, fix duplicated content
  .gitignore
  .pre-commit-config.yaml
  app/consoles/package.json
  app/edit/package.json
  app/jupyter-lite.json
  app/lab/package.json
  app/notebooks/package.json
  app/repl/package.json
  app/tree/package.json
  py/jupyterlite-core/jupyterlite_core/addons/contents.py
  yarn.lock
Labels: bug

#1178 Fix file indexing that caused content duplication
  py/jupyterlite-core/jupyterlite_core/addons/contents.py
Labels: bug

#1181 Fix deprecation warning in the Altair example
  examples/pyodide/altair.ipynb
Labels: documentation
