Repository jupyterlite/jupyterlite, pull requests merged in 2023-04, with the labels that each got.

#1034 Fix chunk handling when uploading notebooks
  packages/contents/src/contents.ts
Labels: bug

#1035 Update to `jupyterlite-pyodide-kernel==0.0.6` on RTD
  examples/jupyter_lite_config.json
Labels: documentation

#950 Add back `plotly` to the examples
  .binder/environment.yml
  examples/jupyter_lite_config.json
  examples/pyodide/plotly.ipynb
Labels: documentation

#1039 Add missing `LICENSE` to the `jupyterlite` metapackage
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/LICENSE
  py/jupyterlite/pyproject.toml
Labels: maintenance

#1044 Add a guide for opening a file from an external URL to the documentation
  docs/howto/content/open-url-parameter.md
  docs/howto/index.md
Labels: documentation

#1051 Add download button as example settings
  docs/howto/configure/settings.md
Labels: documentation

#1054 Add warning to the RTC documentation
  docs/howto/configure/rtc.md
Labels: documentation

#1058 Mention the Python kernels run in a Web Worker
  docs/howto/configure/kernels.md
Labels: documentation

#1059 Mention `jupyter-lite.json` in the pyodide docs
  docs/howto/pyodide/pyodide.md
Labels: documentation

#1060 DOC Fix typo in cli.ipynb
  docs/reference/cli.ipynb
Labels: documentation

#1061 DOC Make documentation about source maps more accurate
  docs/howto/configure/advanced/optimizations.md
Labels: documentation

#1062 Add more documentation for config files
  docs/howto/configure/config_files.md
  docs/howto/configure/latex.md
  docs/howto/configure/settings.md
  docs/howto/index.md
Labels: documentation

#1066 Fix dead link in the documentation
  docs/howto/configure/kernels.md
Labels: documentation
