Repository jupyterlite/jupyterlite, pull requests merged in 2023-08, with the labels that each got.

#1118 Do not stub out the native WebSocket
  packages/kernel/src/kernels.ts
Labels: enhancement

#1120 Update to `jupyterlite-pyodide-kernel==0.1.0` on RTD
  examples/jupyter_lite_config.json
Labels: documentation

#1075 Only handle broadcasted messages meant to be received
  packages/contents/src/broadcast.ts
  packages/contents/src/drivefs.ts
  packages/server/src/service-worker.ts
Labels: bug

#1130 Update to jupyterlite-pyodide-kernel==0.1.1 on RTD
  examples/jupyter_lite_config.json
Labels: documentation
