Repository jupyterlite/jupyterlite, pull requests merged in 2024-03, with the labels that each got.

#1330 Bump to `jupyterlab-tour==4.0.1`
  .binder/environment.yml
  docs/howto/configure/simple_extensions.md
  examples/jupyter_lite_config.json
Labels: maintenance

#1343 [0.2.x] Bump to `jupyterlite-pyodide-kernel==0.2.3` in the demo site
  examples/jupyter_lite_config.json
Labels: documentation

#1336 Unregistering old service workers when there is a new version
  packages/server/src/service-manager.ts
Labels: bug

#1349 Update to JupyterLab 4.1.5 and Notebook 7.1.2
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance

#1316 Add an option to enable the service worker cache
  app/jupyterlite.schema.v0.json
  docs/migration.md
  packages/server/src/service-manager.ts
  packages/server/src/service-worker.ts
Labels: bug

#1355 Update to Python 3.11 for the dev environment
  .binder/environment.yml
  CONTRIBUTING.md
  docs/environment.yml
Labels: maintenance

#1352 Add troubleshooting page to the documentation
  docs/index.md
  docs/troubleshooting.md
Labels: documentation

#1356 Update releaser workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance
