Repository jupyterlite/jupyterlite, pull requests merged in 2024-01, with the labels that each got.

#1269 Handle missing `all_federated.json`
  app/webpack.config.js
  packages/settings/src/settings.ts
  py/jupyterlite-core/jupyterlite_core/addons/federated_extensions.py
Labels: bug

#1281 Group dependabot updates
  .github/dependabot.yml
Labels: maintenance

#1287 Fix typo in docs for adding custom file type
  docs/howto/content/files.md
Labels: documentation

#1289 Update vercel-netlify.md
  docs/howto/deployment/vercel-netlify.md
Labels: documentation

#1225 Add contributors to the README
  README.md
Labels: documentation

#1290 Update the IFrame guide to reference the JupyterLab extension template
  docs/howto/configure/advanced/iframe.md
  docs/howto/extensions/frontend.md
Labels: documentation

#1297 Update to JupyterLab 4.0.11 and Notebook 7.0.7
  .binder/environment.yml
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/javascript-kernel/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite-javascript-kernel/package.json
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#1293 Initiate documentation on the kernel contents
  docs/conf.py
  docs/environment.yml
  docs/reference/architecture.md
  docs/reference/contents.md
  docs/reference/index.md
  requirements-docs.txt
Labels: documentation
