Repository jupyterlite/jupyterlite, pull requests merged in 2024-07, with the labels that each got.

#1428 Mention `jupyterlite-pyodide-kernel` supports the `SharedArrayBuffer` in the documentation
  docs/howto/content/python.md
Labels: documentation

#1434 Updated integration tests workflow
  .github/workflows/playwright-update.yml
Labels: maintenance

#1439 Update to JupyterLab 4.2.4
  .binder/environment.yml
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  yarn.lock
Labels: enhancement

#1426 Remove pin on `importlib_metadata`
  .binder/environment.yml
  docs/environment.yml
  requirements-build.txt
Labels: maintenance

#1442 Mention file access via `SharedArrayBuffer` in the migration guide
  docs/migration.md
Labels: documentation

#1446 Fix tbump rule
  pyproject.toml
Labels: maintenance

#1443 docs: update config file example with correct output dir parameter name
  docs/howto/configure/config_files.md
Labels: documentation
