Repository jupyterlite/jupyterlite, pull requests merged in 2024-12, with the labels that each got.

#1531 Test on Python 3.9 - 3.13 on CI
  .github/workflows/build.yml
  py/jupyterlite-core/jupyterlite_core/addons/icons.py
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
Labels: maintenance

#1524 Fix contents copy stripping part of path
  packages/contents/src/contents.ts
Labels: bug

#1530 Fix file size handling for the contents drive
  packages/contents/src/contents.ts
  packages/contents/src/drivefs.ts
Labels: bug

#1514 Update to JupyterLab 4.3 and Notebook 7.3
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/index.template.html
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  docs/migration.md
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/test/embed.test.ts-snapshots/embed-repl-chromium-linux.png
  ui-tests/test/embed.test.ts-snapshots/embed-repl-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-firefox-linux.png
  ui-tests/test/kernels.spec.ts
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-firefox-linux.png
  ui-tests/test/notebook.test.ts
  ui-tests/test/notebook.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/notebook.test.ts-snapshots/notebook-as-json-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/notebook-as-json-firefox-linux.png
  ui-tests/test/notebook.test.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/repl.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/repl.test.ts-snapshots/page-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/page-firefox-linux.png
  ui-tests/test/utils.ts
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#1462 Update to Python 3.12 for the dev environment and CI
  .binder/environment.yml
  CONTRIBUTING.md
  docs/environment.yml
Labels: maintenance

#1537 Drop Python 3.8
  .binder/environment.yml
  docs/conf.py
  docs/migration.md
  package.json
  py/jupyterlite-core/jupyterlite_core/__init__.py
  py/jupyterlite-core/jupyterlite_core/addons/__init__.py
  py/jupyterlite-core/jupyterlite_core/addons/archive.py
  py/jupyterlite-core/jupyterlite_core/addons/base.py
  py/jupyterlite-core/jupyterlite_core/addons/contents.py
  py/jupyterlite-core/jupyterlite_core/addons/federated_extensions.py
  py/jupyterlite-core/jupyterlite_core/addons/icons.py
  py/jupyterlite-core/jupyterlite_core/addons/lite.py
  py/jupyterlite-core/jupyterlite_core/addons/mimetypes.py
  py/jupyterlite-core/jupyterlite_core/addons/report.py
  py/jupyterlite-core/jupyterlite_core/addons/serve.py
  py/jupyterlite-core/jupyterlite_core/addons/settings.py
  py/jupyterlite-core/jupyterlite_core/addons/static.py
  py/jupyterlite-core/jupyterlite_core/addons/translation.py
  py/jupyterlite-core/jupyterlite_core/app.py
  py/jupyterlite-core/jupyterlite_core/config.py
  py/jupyterlite-core/jupyterlite_core/constants.py
  py/jupyterlite-core/jupyterlite_core/manager.py
  py/jupyterlite-core/jupyterlite_core/optional.py
  py/jupyterlite-core/jupyterlite_core/tests/test_archive.py
  py/jupyterlite-core/jupyterlite_core/tests/test_cli.py
  py/jupyterlite-core/jupyterlite_core/tests/test_contents.py
  py/jupyterlite-core/jupyterlite_core/tests/test_extend_addon.py
  py/jupyterlite-core/jupyterlite_core/tests/test_federated.py
  py/jupyterlite-core/jupyterlite_core/tests/test_meta.py
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/jupyterlite/__init__.py
  py/jupyterlite/jupyterlite/addons/base.py
  py/jupyterlite/jupyterlite/constants.py
  py/jupyterlite/pyproject.toml
  pyproject.toml
  requirements-lint.txt
Labels: maintenance

#1538 Fix handling of sessions and kernels restarts
  app/lab/package.json
  docs/migration.md
  packages/kernel/package.json
  packages/kernel/src/kernels.ts
  packages/kernel/src/tokens.ts
  packages/server/package.json
  packages/session/src/sessions.ts
  ui-tests/test/kernels.spec.ts
  yarn.lock
Labels: bug

#1545 Update to JupyterLab 4.3.4 and Notebook 7.3.2
  .binder/environment.yml
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#1539 Add Zulip badge to the README
  README.md
  py/jupyterlite/README.md
Labels: maintenance

#1546 Bump `jupyterlite-pyodide-kernel`
  .binder/environment.yml
  examples/jupyter_lite_config.json
  ui-tests/requirements.txt
Labels: maintenance
