Repository jupyterlite/jupyterlite, pull requests merged in 2024-06, with the labels that each got.

#1383 Allow providing your own ContentsAPI implementation for the emscripten DriveFS
  docs/migration.md
  packages/contents/src/broadcast.ts
  packages/contents/src/drivecontents.ts
  packages/contents/src/drivefs.ts
  packages/contents/src/emscripten.ts
  packages/contents/src/index.ts
Labels: enhancement

#1405 Add docs about the use of `SharedArrayBuffer`
  docs/howto/content/python.md
  docs/howto/deployment/vercel-netlify.md
Labels: documentation

#1418 Fix some drive methods return types
  packages/contents/src/drivecontents.ts
  packages/contents/src/drivefs.ts
Labels: bug

#1419 Add `packageManager` to `package.json`
  package.json
  ui-tests/package.json
Labels: maintenance

#1420 Update to JupyterLab 4.2.2
  .binder/environment.yml
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#1423 Reduce final package size, start updating demo
  .binder/environment.yml
  .github/workflows/build.yml
  .github/workflows/ui-tests.yml
  .github/workflows/win-dev.yml
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/repl/package.json
  app/tree/package.json
  docs/conf.py
  docs/environment.yml
  dodo.py
  examples/jupyter_lite_config.json
  package.json
  requirements-build.txt
  yarn.lock
Labels: enhancement

#1425 Update to JupyterLab 4.2.3
  .binder/environment.yml
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  yarn.lock
Labels: enhancement
