Repository jupyterlite/jupyterlite, pull requests merged in 2024-05, with the labels that each got.

#1376 Update to JupyterLab 4.2 and Notebook 7.2
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  docs/migration.md
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/application/src/singleWidgetShell.ts
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/test/embed.test.ts-snapshots/embed-repl-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/kernels.spec.ts
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/csvviewer-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/notebook.test.ts-snapshots/imageviewer-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/notebook-as-json-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/renderers.test.ts-snapshots/latex-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/page-chromium-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#1391 Fix playwright update workflow
  .github/workflows/playwright-update.yml
Labels: maintenance

#1390 Update UI-tests snapshots
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-firefox-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-firefox-linux.png
  ui-tests/test/notebook.test.ts-snapshots/csvviewer-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/notebook.test.ts-snapshots/imageviewer-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/notebook-as-json-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/repl.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/repl.test.ts-snapshots/page-firefox-linux.png
Labels: maintenance

#1392 Bump `ejs`
  yarn.lock
Labels: maintenance

#1394 Add note about `currentChanged` to the migration guide
  docs/migration.md
Labels: documentation

#1397 Add `@jupyterlab/terminal-extension`
  app/lab/package.json
  yarn.lock
Labels: enhancement

#1400 Update to Jupyterlab 4.2.1
  .binder/environment.yml
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  yarn.lock
Labels: enhancement

#1395 DriveFS: Handle receiving a stream instead of a node
  docs/migration.md
  packages/contents/src/drivefs.ts
  packages/contents/src/emscripten.ts
Labels: enhancement, api-change
