Repository jupyterlite/jupyterlite, pull requests merged in 2024-10, with the labels that each got.

#1481 Add a partially functional local event manager
  packages/server/src/app.ts
Labels: enhancement

#1489 Ping service worker every 20s
  packages/server/src/service-manager.ts
  packages/server/src/service-worker.ts
Labels: bug

#1491 Fix deployment issue by removing reliance on .bashrc for Vercel and Netlify environments
  docs/howto/deployment/vercel-netlify.md
Labels: documentation

#1494 Update `LocalEventManager` to emit an `Event.Emission` that mimics the back-end
  packages/server/src/app.ts
Labels: bug

#1497 handle binary file chunks
  packages/contents/src/contents.ts
Labels: bug

#1495 Service worker unregistering should be completed before registering new service worker
  packages/server/src/service-manager.ts
Labels: bug

#1509 Align kernel URL for server with client kernel URL
  packages/kernel/src/kernels.ts
Labels: bug
