Repository jupyterlite/jupyterlite, pull requests merged in 2024-02, with the labels that each got.

#1306 Pin to `jupyterlab<4.1.0`
  .binder/environment.yml
  CONTRIBUTING.md
  docs/environment.yml
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite-javascript-kernel/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
Labels: maintenance

#1309 Pin `pytest<8` for pypy
  .github/workflows/build.yml
Labels: maintenance

#1305 Fix a few typos in documentation
  docs/howto/configure/advanced/extensions.md
  docs/howto/configure/config_files.md
  docs/howto/configure/interface_switcher.md
  docs/howto/configure/simple_extensions.md
  docs/howto/extensions/cli-addons.md
  docs/migration.md
  docs/quickstart/configure.md
  docs/quickstart/using.md
  examples/pyodide/python-packages.ipynb
Labels: documentation

#1310 Update xeus python documentation
  CONTRIBUTING.md
  docs/howto/configure/kernels.md
  docs/howto/extensions/kernel.md
  docs/howto/xeus-python/preinstalled_packages.md
  docs/migration.md
  docs/quickstart/using.md
Labels: documentation

#1313 Remove `jupyterlite-javascript-kernel`
  .github/workflows/build.yml
  .gitignore
  app/kernelspecs/javascript.svg
  docs/howto/extensions/frontend.md
  docs/migration.md
  docs/quickstart/using.md
  dodo.py
  examples/javascript.ipynb
  examples/jupyter_lite_config.json
  package.json
  packages/_metapackage/package.json
  packages/_metapackage/src/index.ts
  packages/_metapackage/tsconfig.json
  packages/javascript-kernel/babel.config.js
  packages/javascript-kernel/jest.config.js
  packages/javascript-kernel/package.json
  packages/javascript-kernel/src/comlink.worker.ts
  packages/javascript-kernel/src/index.ts
  packages/javascript-kernel/src/kernel.ts
  packages/javascript-kernel/src/tokens.ts
  packages/javascript-kernel/src/worker.ts
  packages/javascript-kernel/style/base.css
  packages/javascript-kernel/style/index.css
  packages/javascript-kernel/style/index.js
  packages/javascript-kernel/test/jskernel.spec.ts
  packages/javascript-kernel/tsconfig.json
  packages/javascript-kernel/tsconfig.test.json
  py/jupyterlite-javascript-kernel/LICENSE
  py/jupyterlite-javascript-kernel/README.md
  py/jupyterlite-javascript-kernel/jupyterlite_javascript_kernel/__init__.py
  py/jupyterlite-javascript-kernel/package.json
  py/jupyterlite-javascript-kernel/pyproject.toml
  py/jupyterlite-javascript-kernel/setup.py
  py/jupyterlite-javascript-kernel/src/index.ts
  py/jupyterlite-javascript-kernel/tsconfig.json
  py/jupyterlite/pyproject.toml
  pyproject.toml
  requirements-editable.txt
  tsconfig.typedoc.json
  typedoc.json
  ui-tests/package.json
  ui-tests/requirements.txt
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-firefox-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-firefox-linux.png
  yarn.lock
Labels: maintenance

#1314 Bump UI tests dependencies
  ui-tests/requirements.txt
Labels: maintenance

#1325 Enable the notifications plugin in Notebook 7
  app/consoles/package.json
  app/edit/package.json
  app/notebooks/package.json
  app/repl/package.json
  app/tree/package.json
Labels: enhancement

#1326 Update offline guide to mention xeus python
  docs/howto/configure/advanced/offline.md
Labels: documentation

#1327 Update to the JupyterLab 4.1.2 and Notebook 7.1.1 packages
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#1258 Re-add `jupyterlab-tour`
  .binder/environment.yml
  docs/howto/configure/simple_extensions.md
  examples/jupyter_lite_config.json
Labels: documentation, upstream

#1329 Mock `/api/config` endpoint
  packages/server-extension/src/index.ts
Labels: maintenance
