Repository jupyterlite/jupyterlite, pull requests merged in 2025-06, with the labels that each got.

#1668 remove top copyright years
  LICENSE
  docs/conf.py
  packages/application-extension/src/index.tsx
  py/jupyterlite-core/LICENSE
  py/jupyterlite/LICENSE
Labels: documentation

#1669 Document how to test package compatibility
  docs/troubleshooting.md
Labels: documentation

#1671 Stop execution when an error occurs on "Restart Kernel and Run All Cells"
  packages/kernel/src/client.ts
  ui-tests/contents/runall-error.ipynb
  ui-tests/test/kernels.spec.ts
Labels: bug

#1672 docs: Update deployment instructions for Vercel and Netlify
  docs/howto/deployment/vercel-netlify.md
Labels: documentation

#1673 Backport PR #1672 on branch 0.6.x (docs: Update deployment instructions for Vercel and Netlify)
  docs/howto/deployment/vercel-netlify.md
Labels: documentation

#1675 Fix the failing `win-dev` CI check
  .github/workflows/win-dev.yml
Labels: maintenance

#1674 Implement `BrowserStorageDrive.getDownloadUrl()`
  packages/contents/src/drive.ts
  ui-tests/test/contents.spec.ts
Labels: bug

#1677 Backport PR #1674 on branch 0.6.x (Implement `BrowserStorageDrive.getDownloadUrl()`)
  packages/contents/src/drive.ts
  ui-tests/test/contents.spec.ts
Labels: bug

#1680 Update to JupyterLab 4.4.4 and Notebook 7.4.4
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/apputils-extension/package.json
  packages/apputils/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server/package.json
  packages/services-extension/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance
