Repository jupyterlite/jupyterlite, pull requests merged in 2025-03, with the labels that each got.

#1593 Add the plugin manager
  app/index.template.js
  packages/application-extension/package.json
  packages/application-extension/src/index.tsx
  packages/application-extension/src/pluginmanager.ts
  yarn.lock
Labels: enhancement

#1591 Fix memoryStorageDriver in jupyterlite.schema.v0.json
  app/jupyterlite.schema.v0.json
Labels: documentation

#1597 Update to JupyterLab 4.4.0b2 and Notebook 7.4.0b2
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/kernel/src/connection.ts
  packages/kernel/src/index.ts
  packages/kernel/src/kernelspecclient.ts
  packages/kernel/src/kernelspecsmanager.ts
  packages/kernel/src/manager.ts
  packages/kernel/src/tokens.ts
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server/package.json
  packages/services-extension/package.json
  packages/services-extension/src/index.ts
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/translation/src/connector.ts
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/requirements.txt
  yarn.lock
Labels: enhancement

#1598 Remove custom `IServerSettings` plugin
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/repl/package.json
  app/tree/package.json
  packages/services-extension/src/index.ts
Labels: maintenance

#1602 Refresh specs when new JupyterLite kernels are added
  packages/kernel/src/kernelspecs.ts
  packages/kernel/src/tokens.ts
  packages/services-extension/src/index.ts
Labels: bug

#1603 Update to JupyterLab 4.4.0rc0 and Notebook 7.4.0b3
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server/package.json
  packages/services-extension/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/requirements.txt
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#1606 Handle Drive.get exceptions for missing content
  packages/contents/src/drive.ts
Labels: bug
