Repository jupyterlite/jupyterlite, pull requests merged in 2025-01, with the labels that each got.

#1547 Allow not executing code with the repl
  docs/quickstart/embed-repl.md
  packages/repl-extension/src/index.ts
  ui-tests/test/repl.test.ts
  ui-tests/test/repl.test.ts-snapshots/populate-prompt-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/populate-prompt-firefox-linux.png
Labels: enhancement

#1550 Increase nbformat_minor to 5 in contents package
  packages/contents/src/contents.ts
Labels: enhancement

#1555 Fix typo
  docs/howto/configure/simple_extensions.md
  docs/quickstart/standalone.md
Labels: documentation

#1558 Fix typo in CLI addons doc
  docs/howto/extensions/cli-addons.md
Labels: documentation

#1560 Troubleshoot UI tests
  ui-tests/test/embed.test.ts-snapshots/embed-repl-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/csvviewer-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/imageviewer-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/notebook-as-json-chromium-linux.png
  ui-tests/test/notebook.test.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/renderers.test.ts-snapshots/latex-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/page-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/populate-prompt-chromium-linux.png
Labels: maintenance

#1559 Bump `jupyterlite-pyodide-kernel`
  .binder/environment.yml
  .github/workflows/ui-tests.yml
  examples/jupyter_lite_config.json
  ui-tests/requirements.txt
Labels: maintenance

#1561 Update to JupyterLab 4.4 and Notebook 7.4
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/requirements.txt
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#1569 Backport PR #1568 on branch 0.5.x (Emscripten DriveFS: Use ErronoError instead of genericErrors in the lookup function)
  packages/contents/src/drivefs.ts
Labels: bug
