Repository jupyterlite/jupyterlite, pull requests merged in 2025-09, with the labels that each got.

#1715 Fix: Drive issue when writing a previously created + deleted file
  examples/jupyter_lite_config.json
  packages/contents/src/drivecontents.ts
  packages/contents/src/drivefs.ts
  packages/contents/src/emscripten.ts
  ui-tests/contents/file-access-4.ipynb
  ui-tests/requirements.txt
  ui-tests/test/service-worker.spec.ts
Labels: bug

#1720 Update to `jupyterlite-pyodide-kernel==0.7.0a2`
  examples/jupyter_lite_config.json
  ui-tests/requirements.txt
Labels: maintenance

#1730 Pin pytest-cov <7
  .binder/environment.yml
  app/lab/favicon.ico
  docs/environment.yml
  py/jupyterlite-core/pyproject.toml
  requirements-test.txt
Labels: maintenance

#1723 Throw EINVAL (28) in `DriveFSEmscriptenNodeOps.readlink`
  examples/jupyter_lite_config.json
  packages/contents/src/drivefs.ts
  ui-tests/requirements.txt
  ui-tests/test/contents.spec.ts
Labels: bug

#1736 Backport PR #1725 on branch 0.6.x (Add xeus-r kernel to the documentation)
  docs/howto/index.md
  docs/howto/xeus-r/preinstalled_packages.md
  docs/quickstart/using.md
Labels: documentation

#1734 Improve Installing other kernels section from documentation
  CONTRIBUTING.md
Labels: documentation

#1742 Correct use of EINVAL
  packages/contents/src/drivefs.ts
  ui-tests/test/contents.spec.ts
Labels: bug
