Repository jupyterlite/jupyterlite, pull requests merged in 2025-04, with the labels that each got.

#1611 Add `doit dev` command to CONTRIBUTING docs
  CONTRIBUTING.md
Labels: documentation

#1619 Update to JupyterLab 4.4 and Jupyter Notebook 7.4
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server/package.json
  packages/services-extension/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/types/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/requirements.txt
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#1623 Fix typo in notebook requirement
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
Labels: maintenance

#1621 `BroadcastChannel` with identifier to properly send responses from the Service Worker
  docs/howto/configure/advanced/extensions.md
  docs/migration.md
  docs/reference/contents.md
  examples/jupyter_lite_config.json
  packages/application-extension/src/index.tsx
  packages/application-extension/tsconfig.json
  packages/contents/src/drivefs.ts
  packages/server/src/service-worker-manager.ts
  packages/server/src/service-worker.ts
  packages/server/src/tokens.ts
  ui-tests/contents/file-access.ipynb
  ui-tests/requirements.txt
  ui-tests/test/service-worker.test.ts
Labels: bug

#1624 Update to `jupyterlite-pyodide-kernel==0.6.0a5`
  examples/jupyter_lite_config.json
  ui-tests/requirements.txt
Labels: maintenance

#1620 Remove top-level `resolutions`
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/repl/package.json
  app/tree/package.json
  docs/reference/api/index.md
  dodo.py
  package.json
  typedoc.json
  yarn.lock
Labels: maintenance

#1612 Fix handling of contents when multiple lite sites are shared under the same host
  app/jupyterlite.schema.v0.json
  docs/howto/configure/storage.md
  docs/howto/content/files.md
  docs/migration.md
  packages/services-extension/src/index.ts
Labels: enhancement

#1627 Fix concurrent file system access from multiple tabs
  packages/server/src/service-worker-manager.ts
  packages/server/src/service-worker.ts
  ui-tests/contents/file-access-1.ipynb
  ui-tests/contents/file-access-2.ipynb
  ui-tests/contents/file-access.ipynb
  ui-tests/test/service-worker.test.ts
Labels: bug

#1628 Stabilize UI tests
  ui-tests/test/notebook.test.ts
Labels: maintenance

#1630 Use consistent filenames for UI test
  ui-tests/test/contents.spec.ts
  ui-tests/test/embed.spec.ts
  ui-tests/test/embed.spec.ts-snapshots/embed-repl-chromium-linux.png
  ui-tests/test/embed.spec.ts-snapshots/embed-repl-firefox-linux.png
  ui-tests/test/general.spec.ts
  ui-tests/test/general.spec.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.spec.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.spec.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/general.spec.ts-snapshots/simple-mode-firefox-linux.png
  ui-tests/test/nojs.spec.ts
  ui-tests/test/notebook.spec.ts
  ui-tests/test/notebook.spec.ts-snapshots/csvviewer-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/csvviewer-firefox-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/imageviewer-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/imageviewer-firefox-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/notebook-as-json-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/notebook-as-json-firefox-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/notebook.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/renderers.spec.ts
  ui-tests/test/renderers.spec.ts-snapshots/latex-chromium-linux.png
  ui-tests/test/renderers.spec.ts-snapshots/latex-firefox-linux.png
  ui-tests/test/repl.spec.ts
  ui-tests/test/repl.spec.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/repl.spec.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/repl.spec.ts-snapshots/page-chromium-linux.png
  ui-tests/test/repl.spec.ts-snapshots/page-firefox-linux.png
  ui-tests/test/repl.spec.ts-snapshots/populate-prompt-chromium-linux.png
  ui-tests/test/repl.spec.ts-snapshots/populate-prompt-firefox-linux.png
  ui-tests/test/service-worker.spec.ts
  ui-tests/test/translations.spec.ts
Labels: maintenance

#1631 Update to JupyterLab 4.4.1 and Notebook 7.4.1
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server/package.json
  packages/services-extension/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/requirements.txt
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#1633 Add `preserve="true"` to `<reference>`
  packages/contents/src/emscripten.ts
  packages/server/src/service-worker.ts
Labels: maintenance

#1634 Fix a couple of `TODO` items
  packages/apputils-extension/src/index.tsx
  packages/apputils/src/licenses.ts
  packages/apputils/src/translation.ts
Labels: maintenance
