Repository jupyterlite/jupyterlite, pull requests merged in 2025-08, with the labels that each got.

#1691 Increase timeouts and retries in tests
  py/jupyterlite-core/jupyterlite_core/tests/test_serve.py
Labels: maintenance

#1692 Backport PR #1691 on branch 0.6.x (Increase timeouts and retries in tests)
  py/jupyterlite-core/jupyterlite_core/tests/test_serve.py
Labels: maintenance

#1688 use bound instance methods for DriveFSEmscriptenNodeOps
  packages/contents/src/drivefs.ts
Labels: enhancement

#1683 Add basic interrupt functionality
  packages/kernel/src/client.ts
  ui-tests/contents/runall-interrupt.ipynb
  ui-tests/test/kernels.spec.ts
Labels: bug

#1693 [0.6.x] Update to JupyterLab 4.4.5 and Notebook 7.4.5
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/apputils-extension/package.json
  packages/apputils/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server/package.json
  packages/services-extension/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#1703 Backport PR #1702 on branch 0.6.x (allow-bubbling-down)
  app/index.template.js
Labels: bug

#1694 Update to `jupyterlite-pyodide-kernel==0.7.0a1`
  examples/jupyter_lite_config.json
  ui-tests/requirements.txt
  ui-tests/test/kernels.spec.ts
Labels: maintenance

#1716 Backport PR #1714 on branch 0.6.x (Fix: Drive issue on rewritting JSON file)
  packages/contents/src/drivecontents.ts
  ui-tests/contents/file-access-3.ipynb
  ui-tests/test/service-worker.spec.ts
Labels: bug
