Repository jupyterlite/jupyterlite, pull requests merged in 2025-05, with the labels that each got.

#1636 Add a loading indicator
  app/bootstrap.js
  app/index.template.html
  app/index.template.js
  app/jupyterlite.schema.v0.json
  app/lab/jupyter-lite.json
  ui-tests/test/page.spec.ts
Labels: enhancement

#1638 Add a plugin to clear browser data (settings and files)
  docs/troubleshooting.md
  packages/application-extension/package.json
  packages/application-extension/schema/clear-browser-data.json
  packages/application-extension/src/clear-data-dialog.tsx
  packages/application-extension/src/index.tsx
  packages/application-extension/style/base.css
  packages/contents/src/drive.ts
  packages/settings/src/settings.ts
  ui-tests/test/contents.spec.ts
Labels: enhancement

#1645 Remove triple slash references
  packages/contents/src/emscripten.ts
  packages/contents/tsconfig.json
  packages/server/package.json
  packages/server/src/service-worker.ts
  packages/server/tsconfig.json
  yarn.lock
Labels: maintenance

#1642 Toolbar item to show the kernel logs
  .gitignore
  .yarn/patches/@jupyterlab-fileeditor-extension-npm-4.4.2-8e26958be6.patch
  docs/images/jupyterlite-kernel-status.png
  docs/troubleshooting.md
  examples/jupyter_lite_config.json
  package.json
  packages/apputils-extension/package.json
  packages/apputils-extension/schema/kernel-status.json
  packages/apputils-extension/src/index.tsx
  packages/apputils-extension/src/kernelstatus.tsx
  packages/apputils-extension/style/base.css
  packages/apputils-extension/style/index.css
  packages/apputils-extension/style/index.js
  ui-tests/requirements.txt
  ui-tests/test/kernels.spec.ts
  yarn.lock
Labels: enhancement

#1648 Update docs for interacting with JupyterLite in an IFrame
  docs/howto/configure/advanced/iframe.md
Labels: documentation

#1649 Improve kernel logs docs
  docs/troubleshooting.md
Labels: documentation

#1650 Bump to `jupyterlite-pyodide-kernel==0.6.0b1`
  examples/jupyter_lite_config.json
  ui-tests/requirements.txt
Labels: maintenance

#1655 Fix user facing changelog
  docs/changelog.md
Labels: documentation

#1654 Rename service-worker broadcast channel to something more general
  docs/migration.md
  docs/reference/contents.md
  packages/contents/src/drivefs.ts
  packages/server/src/service-worker-manager.ts
  packages/server/src/service-worker.ts
Labels: enhancement, api-change

#1658 Update to JupyterLab 4.4.3 and Notebook 7.4.3
  .binder/environment.yml
  .yarn/patches/@jupyterlab-fileeditor-extension-npm-4.4.2-8e26958be6.patch
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/apputils-extension/package.json
  packages/apputils/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server/package.json
  packages/services-extension/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  yarn.lock
Labels: maintenance

#1659 Remove `registerPluginModule` methods from `SingleAppWidget`
  docs/migration.md
  packages/application/src/singleWidgetApp.ts
Labels: maintenance, api-change
