Repository jupyterlite/jupyterlite, pull requests merged in 2025-02, with the labels that each got.

#1570 Update to JupyterLab `4.4.0a3` and Notebook `7.4.0a2`
  .binder/environment.yml
  CONTRIBUTING.md
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  examples/jupyter_lite_config.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/repl-extension/schema/buttons.json
  packages/repl-extension/src/index.ts
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/requirements.txt
  ui-tests/test/embed.test.ts-snapshots/embed-repl-chromium-linux.png
  ui-tests/test/embed.test.ts-snapshots/embed-repl-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-firefox-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-firefox-linux.png
  ui-tests/test/notebook.test.ts-snapshots/notebook-as-json-firefox-linux.png
  ui-tests/test/repl.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/repl.test.ts-snapshots/page-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/page-firefox-linux.png
  ui-tests/test/repl.test.ts-snapshots/populate-prompt-chromium-linux.png
  ui-tests/test/repl.test.ts-snapshots/populate-prompt-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#1574 Update to Notebook 7.4.0a3
  .binder/environment.yml
  app/consoles/package.json
  app/edit/package.json
  app/notebooks/package.json
  app/tree/package.json
  docs/environment.yml
  packages/notebook-application-extension/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  yarn.lock
Labels: enhancement

#1577 [DOC] Update Python version in vercel/netlify docs
  docs/howto/deployment/vercel-netlify.md
Labels: documentation

#1580 Pin on `sphinx<8.2` to the fix docs build
  docs/environment.yml
  requirements-docs.txt
Labels: maintenance

#1581 Backport PR #1580 on branch 0.5.x (Pin on `sphinx<8.2` to the fix docs build)
  docs/environment.yml
  requirements-docs.txt
Labels: maintenance

#1578 Update to JupyterLab `4.4.0b0` and Notebook `7.4.0b0`
  .binder/environment.yml
  app/consoles/package.json
  app/edit/package.json
  app/lab/package.json
  app/notebooks/package.json
  app/package.json
  app/repl/package.json
  app/tree/package.json
  docs/environment.yml
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/contents/package.json
  packages/iframe-extension/package.json
  packages/kernel/package.json
  packages/licenses/package.json
  packages/localforage/package.json
  packages/notebook-application-extension/package.json
  packages/repl-extension/package.json
  packages/server-extension/package.json
  packages/server/package.json
  packages/session/package.json
  packages/settings/package.json
  packages/translation/package.json
  packages/ui-components/package.json
  py/jupyterlite-core/pyproject.toml
  py/jupyterlite/pyproject.toml
  requirements-build.txt
  requirements-docs.txt
  requirements-lint.txt
  ui-tests/package.json
  ui-tests/requirements.txt
  ui-tests/test/general.test.ts-snapshots/dark-theme-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/dark-theme-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/launch-firefox-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-chromium-linux.png
  ui-tests/test/general.test.ts-snapshots/simple-mode-firefox-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-chromium-linux.png
  ui-tests/test/kernels.spec.ts-snapshots/default-kernel-name-firefox-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#1573 Expose more REPL options via query string parameters
  docs/quickstart/embed-repl.md
  packages/repl-extension/src/index.ts
Labels: enhancement

#1589 DOC: kernels.md: wording
  docs/howto/configure/kernels.md
Labels: documentation
